name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or any version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate JSON (tables.json)
        run: |
          python main.py

      - name: Generate HTML documentation
        run: |
          python create_doc.py

      - name: Rename documentation.html to index.html
        run: mv documentation.html index.html

      # Deploy to GitHub Pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages      # Branch that will store the static site
          publish_dir: .               # Which folder to push (the repo root in this example)
