name: Generate Power BI Documentation

on:
  repository_dispatch:
    types: [generate-doc]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Python repo
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Documentation
        run: |
          python main.py 
