/// @description Essa tabela é utilizada para armazenar informações sobre as fontes de recursos utilizadas em um determinado orçamento. As colunas CodFonteDetalhado, FonteDetalhado, UOFonte, CodFonte e Cód_Fonte se referem à identificação da fonte de recursos, enquanto as colunas CodIdentificadorUso e IdentificadorUso se referem à finalidade da utilização desses recursos. A coluna CodFonteRecursos se refere à fonte de recursos utilizada para financiar a fonte de recursos principal.
/// @author dsbr
/// @version 1
/// @date 03/11/2022
table Fonte
	lineageTag: ac6ac0a1-0011-4d11-8ffc-e6ad730a48f3

	column CodFonteDetalhado
		dataType: string
		lineageTag: b9f02038-8aa9-4f35-b733-99a6566f2618
		summarizeBy: none
		sourceColumn: CodFonteDetalhado

		annotation SummarizationSetBy = Automatic

	/// @description Nome da fonte
	column FonteDetalhado
		dataType: string
		lineageTag: 639d802b-ab8f-42a2-9d54-a34362f99532
		summarizeBy: none
		sourceColumn: FonteDetalhado

		annotation SummarizationSetBy = Automatic

	/// @description Código UO da fonte
	column UOFonte
		dataType: string
		lineageTag: 87b234a3-b8f6-4637-b8c1-86674642749a
		summarizeBy: none
		sourceColumn: UOFonte

		annotation SummarizationSetBy = Automatic

	/// @description Código da Fonte
	/// @author dsbr
	/// @version 1
	/// @date 03/11/2022
	/// @panel Panorama Orçamentário; Explorar Dados; Serie Histórica; Ind Orçamentário
	column CodFonte
		dataType: string
		lineageTag: b9713cc1-e5d1-4c67-9a4e-e0984fd52a37
		summarizeBy: none
		sourceColumn: CodFonte

		annotation SummarizationSetBy = Automatic

	column CodIdentificadorUso
		dataType: string
		lineageTag: d5b42b8b-04d9-4de4-a6e3-19ff4bf2ec67
		summarizeBy: none
		sourceColumn: CodIdentificadorUso

		annotation SummarizationSetBy = Automatic

	/// @description Identificador do uso do recuros. Exemplo: Recursos não destinados à contrapartida ou à identificação de despesas com ações e serviços públicos de saúde, ou referentes à manutenção e ao desenvolvimento do ensino
	column IdentificadorUso
		dataType: string
		lineageTag: 84ea1f7e-b37d-482c-b14c-1dac6d68d95f
		summarizeBy: none
		sourceColumn: IdentificadorUso

		annotation SummarizationSetBy = Automatic

	column CodFonteRecursos
		dataType: string
		lineageTag: 74d6b5d8-004f-45d1-9acc-9f7175efb33f
		summarizeBy: none
		sourceColumn: CodFonteRecursos

		annotation SummarizationSetBy = Automatic

	/// @description Fonte dos recursos
	column FonteRecursos
		dataType: string
		lineageTag: 787671f8-a036-4707-9d14-0c1b543cc426
		summarizeBy: none
		sourceColumn: FonteRecursos

		annotation SummarizationSetBy = Automatic

	column Cód_Fonte = Fonte[CodFonteRecursos]&" - "&Fonte[FonteRecursos]
		lineageTag: c89d1235-1583-47a3-a770-66b429dd4fa9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Fonte-8f4e8d3b-95ef-495b-be7b-cd270ad06a1a = m
		mode: import
		queryGroup: 'Modelo Orçamentário\Orçamento TG'
		source =
				let
				    Fonte = Csv.Document(Binary.Decompress(Web.Contents(
				        EndTG&TG&"/Fonte.csv.gz"
				        ),Compression.GZip),[Delimiter="	", Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"CodFonte", "CodFonteDetalhado"}, {"Fonte", "FonteDetalhado"}}),
				    #"Primeiros Caracteres Inseridos" = Table.AddColumn(#"Colunas Renomeadas", "CodFonte", each Text.Start([CodFonteDetalhado], 4), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Primeiros Caracteres Inseridos", {"CodFonte"}, SiopFonte, {"Fonte"}, "SiopFonte", JoinKind.LeftOuter),
				    #"SiopFonte Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "SiopFonte", {"CodIdentificadorUso", "IdentificadorUso", "CodFonteRecursos", "FonteRecursos"}, {"CodIdentificadorUso", "IdentificadorUso", "CodFonteRecursos", "FonteRecursos"})
				in
				    #"SiopFonte Expandido"

	annotation PBI_ResultType = Table

