/// @description Ícones de redes social
/// @author dsbr
/// @version 1
/// @date 03/11/2022
table icons
	lineageTag: ac827eba-2cdc-448f-97e7-f097c82d7c25

	column 'Rede Social'
		dataType: string
		lineageTag: 79040cad-d95c-4699-8b85-c8ad651d1eae
		summarizeBy: none
		sourceColumn: Rede Social

		annotation SummarizationSetBy = Automatic

	column base64
		dataType: string
		lineageTag: b2d87262-8e3d-4230-a260-457e3ac51e2a
		summarizeBy: none
		sourceColumn: base64

		annotation SummarizationSetBy = Automatic

	/// @description Número de ordem de cada campo
	column Ordem
		dataType: string
		lineageTag: 4ddf979c-4db3-4386-9b06-a33bdd539fef
		summarizeBy: none
		sourceColumn: Ordem

		annotation SummarizationSetBy = Automatic

	partition icons-1940f414-8b93-4673-957a-e279e43fc5ea = m
		mode: import
		queryGroup: Instagram
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("7LzXrvNqci36Ln1LA8zpYl8wiUHMYjbOBXMOYiaffnP+q9u9eh/7nG7DaBjbS4CmpkTyC1WjqkZpgPrXf/1TOG7rluR/+pc/1R5r2Af0FsuReR76x60Et3z+E63nD9tyTPjzemCT5/78oyMdb8EsG4l0HX3Yjw3J5ZsXcMMpp+f42Ea+uUMz77IfaT/X1xm/fM5Qy5TLbFe8vSM8FR8bS/+98u0XVizcq4We2ApwtJoeywL9pJk6kw5XOrng4M+45y3M0thwL2gFLQz7NphYr2EcEd0wuZ9xEAgXN5zaoxcSh8zIGv3bQ76oywhcdp5sU5BHzcAQQpKNIwIodUlE9GYuvdzOtZPD8g2p4OdrhSerXeWAjBaPcZOzjrAg0Mw3KkgRZt7pTjGfZYYLli1KvbtNG9CMlNHSjmIdFs5ijI3bknT9nHYvYur8TN2UVmibI4+aBbs3G5Bqd3Tg7GW/qGZnEOaUkAOVks5f44umAxAwbSmgEG8boFS2uIN+wR2bv4WtgN3QwM05XLJDtMg9DCY3Uhc0VVOWI7PX2n1fVBVS/EAxhxaZYKE7JvXjREZJhSpKD4bhTu15uziMxcUD+3MsBmLPDrNXpTv81CQItIW+vYe9u+UifDC/PSgTrY7Q1+cosMqw94bYx2h5A8j9ksvYt2i5S2HHYfVU0LtY7OR8UDoXnQxP1IkY0fCIk0GzZqicn7AkYNcosCtZqtZExG9jKGm5f7UJonRG/7zv4S4ThV2uWcwYqjWV7Nn8KH/BWuh4TGkh9BV9GFRthDW8n+1yDGp88Mrg01vzZVzlmEvj5VO9GfzX02EOo9HQ54nJHFP++Vn/rCnt7d7oFMF+5kv8c0vv6YrE8FlTBWUSQ6gXjWZoumW3tiWoMqj3D87b/Rl/1xp5/bleDXQ8Gewq5+AtvbS/jtvaXYroVxywUOzTmywpbdRMVdjTcMZDtfzXOR+7ML+f8xkHr37bM/7jlz0XX8cz96ZxVP1vtuvt5rHNmEn2YdTUnkrelXD4nvbpHonaHvlnl/jelknarn2wU3389fh1SQaNSMVqz0T6jkX6+P0Yz7F/w0CI0KuKsmOC2nuKVHvKUafaMPvfrpvVHQeqY8mGUn7cVQS/1T/7U+31PfnQWBgwP/MfKgKvf7MG1H5lg/V37pu+Pak7og/9iQJ9zwKliVwPiXwckn8b8zBa/Yr8F/T4yU0Qevkdbqxnn8/n+rMXptQa7RmPGT2k257jaHq1v2ya8hOf9l6ViZ4QBnZnfuQfHF0PfpDnCXk/Oa6Rb6Oxft4/r8zxyxYBQzg+3cZ+hNviC4oee2jNg8EaOvSfp2cdWjPemjP++ky7xwezf1nzD95f7TNf9Y9c+/iXiHr6Sp79Pvucntfhsc2R9Omzl9/57NlTgpx72sIPJlxabrT/87hiQbqV9nQfP3j5nc3+Jq//ts8fX09KMuhQ6OOP/TvhOf9n/1vsd63RR72OhGfEW4/NrFsTrVXzXejJ1HUkRu2PzSKnPPTG68Pbbp+V/LKB40KELdJN5sPdE0eK/cTGnzFIPGtpnhzzN3g1GgGP+PDUEa9SnRAx/HCNnkE0Dq71Zw7VD1HdCaGo0Q6916vfz+OgyhQ9fg/9U0gQHf4VH8Jf9xGJzz6aqtN4rzFEvVedEtEcbdVEGTI4CH/mOlRHRnQn6w3fwrUmRMOPDMj8+Rf7yHGg/2AQ/2t+0bvUwUrzt/hf4g97Z4KHZPyTC1B7SpAnn/a/YTfyrcc/OmQHEWT03fbESJX0evdxnzj5yYccPv3YwxDdQ/c1LETC1XhsoV3QETYWpjotHjXM+qwLfnzx2Km99CarHv/9ZU40Fr3t78T2X665EySCMuR1Re6Dsyfm/pHYUu//n70PepX1Xvu7+ab/EGNNVmtOe2hi1KgO2+pO+fhGeHwDV7r/4y/mDBH3ivqoevI0rj++/3OeITKk6pLm74uvv1yTInSfSVn15AU2euryT962fsNm6f4OkzIv309uLN+vbEp6e89QbfrdfppYfG3P9e1j9yd/Uj94+akzRCK2/zbXU2N/1Ylnv3cYRF30u3XEPn4/eeLJyd6v+PjBs9p3U8RPfdRkveZb0LN+SLvZJ85enc6Ha/hgL+KePSEupvEhHPUaFPHyX/E1ZGP0U8sb+fipZc85z9NzH1wQ2i0Qv32mERrP/O4afY8GGw0DpbP87InXB5ftb/lefv2+Vjw2vrBD5qrgWXuboNn9/vx1PyFSPbjOuujZy1MT9p9YUdFfGHGiQHjsc+x/idmP2D17p6/8J4Y4+pfdbNG7wyeWH37wg6Ff5/9bLW9+nfcbfxB/8Ymf42AusVWIrF3GsV3S/8STXJs3NhqgVTw8R3UerFmejQ0GkgXh2dp2IN1359E0ufUejGTdgFiQWGPzVPNs/bJl413KdRia1ktnIps3J2ZshJNKXakRwOt4a7FwU59G+wiA6TNlRZliYzNyaVfYqWid6FVPNKFRzxEkCXtZgQGOmT4YXAvUQz3TWegd+XzIYd3BFJxyItl2z4O/NVlk6/NQ/IccVTZl4OKbl/1lUT7aW2BlxmS+uFdFDXczsNhZTNvdlGqI5iYD+6weIKbvPiuRKft2XmRK4CgpsYJnNZ9ubhTN1k6BfbAn8InFPJQxrdV37zeo1fUWsE9GNON87efKV1UisOXGC6FasG3pw9uqaubDCJJlgLirIv7GPJ0jMCeVMy/1vG4XZnsn30tstOmAlYb43lwWnYJJ46mM6cZZCuyLfU4TrbgCX6QmRA4R6Z94E8mwCMIIuPx3An48rKA/3uzqnK2x4ovgKyYuZch/BetOtOc715Y0tVA14GnxNequc2H7LqTVnAefTbAo40IumjNkvjRbeYkgOAclNszG7GOdDiWsgdeVIPdtucHq0GzKWZOLC9CGptii2Kscy6NhgY/YC6nCvRnctz/G1QlJJlJVGmja7ujvwpY4VzMXqk7V6Ft8YqEAI/nV7SDx3REfUaeEi5uN7gLSSrg0NMpOS/wGrpjDuXXIP7LmbV20qF37qX80YWLrcH+PIm9KhyyE+ZY6vHEOWkx5d9qOTfplGeR9gW/xqwe0ZtFldhDSLfhN6CXBMJxiYjrvEW4ZVvMG5AT4b39EcDhvJbrC5bJdZok0kGQzCD1UB7lPbCPSUjmYwXJLJg1vwIxx8m3jL8oARxioEPYSqTtrliUg33R1WC3gmt8gLQitCA1WpDZqhlIXnN4fNoKKKk7NQMpv95pLZ0+W+o1Nz/aNdpI1Ec+xaoQ9kZC8RDLAYg3GB+MCz5hvKKZ3Z4OGkoczhNZZDH3ZjJ/7QiqiyBmKDJiQipMuBoMLQRN8q9xUqwQ7kLICDSrNaPFEoFAwiq9KeWdsFQPRLIjRJ1nJ8+qPD2ogsXvGHF+qQe06dsZH3Ma8s59NmN5nCZcsttRbEsD0F4xa/v3dT18YaWRUlRygr02cmOU66T58Z4giv9nyjpLd9sG45agMztvM7yXMRLwvAoHR0QRPd2xiJuwnw9PGci9wBbeolgKFrP3ik5GjLzOWYGmhH6ilW/KLToeAlJzgTasr/pi5UhhK1I60lkqD1Sk8cMelmbp3NOED3nV18fW/4BuQCSMwUGwTszieF+dmkxluN9RE2bR0BQ/2cDPaLA5gwxpg2Ep4gu1pWQ7PVY6CGO3tQOYuf01cDSUX+V7X/dOLlIDZAfVVsaDzERLY8q8WOKs7flZ3cGM6VEjOzGF/R88h5IYteIEZ6UmQ8R7KubT011jM7he5wTHpvn6ioZp6vB/qzfZmGZSheGdhqtUpzOlG5+jqO2UC50CX4RhOhBKSSf+VH2hLtvsQmC73dD4ktbOLHebQ6YmwqNeJPfaH3Qhhn2xx/d3siixeLyB1MxlSXaMfkc3wVRe4tIUaJs35PEHQlRrH6+bp2JytWGg9rHWMYEr5rgPVV3Jp4qi3RGzfBQn11mnpeM6kbozBmzv9ImodHhlfQ2eDynsUTjbYDlDSBVZg35w2J5339GW0AJqfsy8FJ08BW//QEf/qtNQNdL2TYPrkNMlMi7thhMHljtZ6ugF3kPt4C/t1UywO66VZ25Vc/phyDWL+154A/+AUZZh5pmBnTbt6KL/sr/VyPFwagNEsrXnEJlT2lXaFeVFv+Kd1Xeg1c/Umaez+ZCVKJVlXVBFNzsaGmDNAMmqLLeFknXvRBZLbllq3jYpiPEbZtVL8rQzU4dKfrnWD4pVBzEDMKv3mjcLpX7uUqyZ+hFGYh60ePzk3bt2tX9iQpewya9unQYmEPjGqkBtBL1NraXaQ62QM7agptG/yfBnJpw2WI/jlf+X7Ku3yK5BuVCwsWk1miC/iYwqletaFPqZa5Fw+ONUZwajTDr5Uf77aYc0UoCD3W2Z1g+jWOK7MMjLtLjqwYiG115+S+8SrrPTwx/6me6pyEVbLYzDZkdG211l2u2hVTrH2LZUrlHG3kWnwruDsE7ArrY0r6zlab7F93954LEgcgcGabcje4/TWpKJQqrzezKnbspetd9RBDNU4T5galKhLt3Vk8RyvDZpNCsbbXOKLFRWsk0s8v4FN4CrpPJZTIRr3Q1vMMn+YOmBTHbhTvRem6ns81KTu/ddoQQzUlx6zxlol2ndRgegmfb7VGQG3TlgM65ZboFyFJAg33EVJh+e9fG00RQbKxBWUw3DtEr01O2DbE3I/8hOXOGG1IahJonEJkB1+yJdv6pCnuydjO6DU9wsYFW4UIGotfHb5O4h+EnJ3OPQvgj2HS3n5xvbd5z5hG8tx8Uvm5FH9wfAr/xLOJNqGu0GI5H5MotWZ1zo3PU3hZi9N00NCH7qXWUq9AHdEMLH8flfbRXr2qJeFT+sxcJ22crGwn1GjPHiLDDPpm51xB1HnppLtpiFD5fPe5m2eayVB6EY1ziYSbMP+gmCXbVc+uH1p9td1O0TZ9/osPoQRCJhLthXyhgTPI4t7njP9taBlWRXEIXDabuRF0UGfBD0b/efcDBAuwR0+/PFivkMEf2/p6svKjKAAaU4bCSe1owfhNDmUm/AWj3WmJehc/ZgMsKsBWQQDym66J7dfJJUweRs3OeuH7mExtv22WrvsLQKx2ncjsr0mCaPsCbVPBvxYTpSmyFJY+tuZaoLVsyyzFX1YC9w7vLNkJh0qFbAFB1w+5dPtxeOgWGgH83op/VzRtnQ29U0b+xVnr6fwrMiXnGZDwawsDyF9rPxmTA36cnffCJxFq1VQyjoCQwHU9/jNgH3ads9CnMdghKZwb7ylC7LNv5PNyqPEyeyUWGpVMofkteFHVgA1L1yk5nRLqoV9IQC7hHZ059/O4rw54KHmPS3g2ueLwEVCcDOITjD5cWaBeu+G6lGvWJIKf/TfpknzxlSIPXnLMHrxxzSycZLPCIZWmZ0t6PuFPgafloeuP+9o4nQNJsx1LQZfGbJQmvt00fEF0ssmfmMLaami2Rwn77WDWjLhFJ+a/15R2MDz7XBEcQLWC6NzLKnnyCitVB/iIcnk/dz56OHFaLrAekRS0gzur0uNsv2yPLl7v0oB2nm9cDLZohYU3NA4OKe60hwgXyaMe3IZqswqL+WDPhVad6XknWVNgbrfZOCcbaOm7Cmb/QajalMtqF7AR4au3bwleO+qLSHxYrTrlYkEEuPzw0SgGsk3GY/CZlyuhkrhSJyWGKJTlISCdKJYcRzCTYC5Vd5LlDnOYnYx8z28QT4K9ZHn72khSA4KBwXU8kmoHYOFrNYR7tZEPc/g34dXXpK/m/Dw8Hnxs9xa4TyQuTzf8+HZS+jTrgj3ARRL0KTjhAD6uUVqcA6j8hwNHCk6Z4+N720wwMiAUgSF/yRIarIJgZETm38cfp1X+hhqudLOmnq9aHBys/f0CouY/Fg34xkbrrKWf0Xoi6bObKvn3Q2kSDr7dChO1P7AYT2oQZfb7Vd++PPXHPHpScZpWwu1FxVn6oWed1Js0yL41Nie6yX1p+YaE0/KLz1s5p4aF2qBIjUe8oDGcNCFemoF9RgDgZdlxCntSwzh/U4TbwexegwYetuME0yVAtiZLJmgiurpZr31nWc41cvrhGKp9UoJAB4OfxS8q+6CBTleJXBAajcvg7ghhbH2RZwM9jyFxyK/UGMQSV3IpPrCAPVo7g5+qIMmbRyMta4+Ivar7cMFUUzP8zF5r1+KsUX5/plZDKJkbpu+A/vgPeGGGdW/1OrTiVEijFZfACe+K0/Q3vOsQjdzP6lFgWRP5Fw7/ywUjJdjMlE0ghIa0xlv1n5IeUGJQ/SUp02R5F9qAKvYLi7MrVKW5f/6X3/6lz/hf/p//uVf/6TWQ5tn9fCHlvQ/WEsKmj+0pD+0pD+0pH+KlgTpzgjr3H9KS/p/XfvfUktq9DbiyztyHvv4GqT/RUv60WDEEFafz8Nef5KN3mu8dhvcf6wl/fZduT1F/HgaTlUZvnCFF4Rq9xNvvozp/MOcfO3nM0y7lUZ3lC70vVZzmN98KcC60dJX7P98t/9a/ivH/5XL/r3vuaXffxf+/6kVNH/G2d+pnzw+EAU8dJRGddJbF8M1bMpf2lZ4/3xW3lqvwdozZuRb5++1kH9XP3lZz57H68ESpP+X6yf/lTrJeEeihWnILz2y0Xn7zzqJtT4+6/UPBOm90oSOe0cNc2t3+XfpJDrvErpj/Q/QSUhQ7473D6dL2r/qJLl/tDaJSsWPfFEUkGRGMXfZ7CIznF87nGCzUi4sH4TTVBHmOethgNVTMplK4erFqsrPW86luTaLT81CpTla9ktgLZlb+jjlEEG8bEbihHKu3UTjyZ5UDYLfyeOc1SAFHc3TQA3ZSQqPBiArYIBeMy/wENBYeaW9sqprXupq60rbndL7A53qzG0xHncCvZR+ibA9oym2rArPvuSW4SxZefkRfLsy/oUX7BhsTS9FaSrFJZrEOQQ0AC2+Nj3CpVU1A32/tHQXunt8pTTwbpFaOZaqlb+X4CqlkZORNzmAZX0jQyZpTaZIEtbttZ56q+J1usHsyhS7V5YThozyJW5CiTPkA13EUGrk4QUr4gzD7UyQVpx0CDfsG+HYiXkV8bmoKkPkEWIwOoMNUps+lSlLmTJtm5S9dhMYM+AtffHgad76Afz6CnvojiDY6LXRU9ZMgYhK5PtpudrLW6BaghS55xgME1nyfeTOx8Y5xEgKWFG0l95iZxWOchjsfZ/VKVVvKhJ6uWOJLfHOMl7GbOZVvSXblhm7mJ0k3QkzpEjhfPXy+BYkHZCOPTw5qLfSSs5hX5JJYcwjOO3b5uq875qJt++3l0pjH1m1sYjuAJgoUA1O3TOPhW9aYUEYRh3UVSVC1ujHQURuUuTlU02FhBWsgO2X5g+1wWGOFdLqXVwGmeWbSr2ltBUPLDsrAyCuOqsq2A9MbqyHCm7SzdPHs0G+Fxx+P9wXBo6PjlaVhDmEh6dY7Ufh0yX0SmWYpKfEs6OwWtu6DuUb32terYW3z0ZpjAbavaqAvtdDqdqXAqOX35MFzqHUS4c5NhRnhJlycVdjmqLIB5ofXybofMNvh4jtr9RhUHLJniHJAemzCgCrrAreq2F8NBWbrG8CuBDQH27Vfr9ESzBaHHWfgtnQIgRMf4zkp4X28tigrhuPFLlFv7WRXdPn07NK/ta3/DK97i28qDz1VQUXVyJTsPGuUz4tJ+uT2xsA7aZCVjOMxk/kGeYZSVrhhTmYJFZZtaIzneBDqtLxoA+oqzVHXAF5LIzIanO4hmr7XJqGAhsexdlYkFH5zQVzR4nSmmzyaGql7afnPECLdYDRBl0WqQ1T+PRN+rIYcq/2ol/I+g7qWuyPjmx9ZPGd3mf19BrydVohU2DTERj7SD3wVB209pBVLH0H9G6ELCWIKamS675x+9XeVzIB8AfIoPoDA/0niNwWOEZst74bbAFqxeNbPYLLUTeEm0pIYXmnymc3IinBF1vkXqFcxJkuQkFSeClMv/Gd51jT8BbZFX1CRfK4s5FlzoMLju9xFDGvc4+qf1mh9Ck3xsH0kGzmb3MZyFIO1QOOPM+hfCUcSBDkb/HglJi52jFOtbiRMZzAsP3upCF2rPpky3qFQX8rp893jfUwjcG3bjppip7LhU7ulNORRfNQa3TIA9Tl3dYk7IXgcbx/ZLn3cmvol+OOFwduwI7iAdh4m63LX41eo9fQ47PfiRl05kWVny8JU3UTXhsvQw570pXt5bwzKMn3z65GAgTE71qUfEE+dxFLYrmt4GIRapmZlAOK2JR5Qj5nXLFXQpqwzyfR1eFUwkvzAY5dm30oFtaj+SR8squDCnSiE6Xu53G9xumaQVW01NqiwN4ctzpb8b0jAOUVNOyG1/TSWY7BOU1atRVAt/RJ9NOTgRhm5bRgPJhCSBwLc4kBEpayA+wouBsKC8u5A4FUrzYpqgTh1X6CQ2AEsXjVA/Xg2I2gD0rO9aUEx3Z80/Z97Pz1EAt4A8T0qc21XjpnYqwTdHQDf6Dt5wRJ0dKYjps9kdLKXqjuNc2QpT6abjNTJuA30VZeWCHWg/0VLcfjrIm7QJwBrVY5yK890dcLbFThUOPdW85LYMVCmyIrRj9UA0l+Fo7HZI2V+i7c5SLOCUfUWn9DlcHl8oOYGX0bPWqvEhR4uKPAH8IzrKkH92yEmpWtJMgJaLJJMxxbGcJfWIa9g8DqHVxMCcgxeUij4moXddhNGp0V6ly7AK3JQDbdR/jTdyzS+0SEr8E9T6/FOGfZxXg9faWfew7ZUigBLOIwy5KQJ1Pam4lhixpaMiMLsj/eDFWXHJNa2OJ8OI70hw++zt/y4A/5p/MfmYPTuIMM1meZez/JtoKBJZ4ei/rK7yD+UnIJcPVYwe93oA9S6FpgUwOGkfcP2ScVX5fsC+EfBD5zMxQbSUrEiy+Br9/jDgpx9KYiWza66NWcztfBBuSn2up+h7UhlEIHVWfX2UqfrQNutibHd8zja8daoknJkQsYsRc8ed77fq77e4Kslod1RmuAFtkLQjChsuuDKRQvWXNYWzeIrAS8Eah3k0POa/MuzFsPQvgU5z3bb8glkbJf1BikoCDJhrOYmOPlckI0jm75BN+pV5762i9XPpYlvW6SEZOHMams+OGR/vLpFbox56nRGYrmRJsp0JqyVmntm3ANEoGohvaNmoIcnESl4tBEs7DSDOZ1uFCJhevuYWKd7w85yeXQsWf1ST4Azx2drInaN2R35OtSxNebkMLAXyIVLxKSCZjhEdlMQpWD93HV7PguU8awtFtjqTGZJQm1bkiAgxJfv9KYUaTP2PZes7pERKCStkHpSAH+O8JTB1f9oiSf0II9zJS/T4MBKm/KdsdtwHlVd984jsc615HFhHKIJeq+gth1g7gLfR/HOdWqw1/wnR05cwmtlkaYtm6YUyhRFTNLpVUZgLmWWHMjzxGIr3KicJ3sa/2i0uidBtzK8A4m1f6JJix0kWkqG9HUWHFxCf9jghwn9FN1ens5Kj8jTARaV7adLGI2yucAUiwWNmhx5dCoQ98hZKP8PKtB+8SC8/QscP0CcIfoK8+3xnLMmRKeSxFViXn5euzAm74+dO47EWBoiMkaQOYmyyJIjSC0UFVrZUPGYpb8fAKIZZSq3S8yDTPBOAffJ048QiRrglEdXMg3RK8c/q5LFQ1X5PFMcH2+2+V+L8CgEr6/E9B/2U0ThviXgpLB/X4qYeKIfax6QmCMVIhjDE5Ql6Zx+mXYi//ywe97gDet/rZXKocXrhRb9Srd029Ns3sJKeG6OFNjBz42ozkROkjDhKk6IauXTe1TdD7Z8SfkCKipSjZuQISS3Xp+Jlco+uqI0IbMzQAW7LwKAic7PotEUYvYfBBfdZTkJRI5EjAhm/Cwwnr6oj5RFt/Ap1GOR25gF1xrB2zQVgcpRco42XJYcWY8JeiZY6C8EBaSWl9VtVK21SjrhYnrA3kYj9s3QkbgCg53V93M1an0RETqPhEiMWRXKJ+eatOZ8gmg4dMrgs5ATgQmyMFZDxR5d1SzA5PJaBtepBtijiy/PaCgfeINUYc5Qp+jYhXr+g4fz9I6tKDXFEHHEUnitjE2jCei6kM+ParLmQzEGw+hpVHYNMHEhJoPuOJv4iEx/OOSXIeLUGLh7TsEVt0WdwZk9ApcwHcm7S1z5z6O/Zyma9EDVYN9wyNyvvAg3uDIa83MXAEedUsnsDIpb78fCenoQFLRbCAlCHNuNAPQvhN19EPCu8l2DzfguFdLV7FJMkwKg989WAuCbq3FA7cYGFhEx+MBTUDqpgnJ20NPEesOJr+Antk+EuzQuZvp9HGeNBud4QugcX7dbVpL82xlRTVBQExf2PJ7ZWoCtK8UIeHQgTby9fZ7lY4CpDqSCA++Cel8HOIh18gsJBKb6/i5F7UzUjA+46imqamb5RieZ9ZahKRrpzDSCmRxDZ/y8mSEQMdlyU4E09f14EMJ6mtv/5g3r5muNpAOWmyvwVmVLjkaTu3EHYnwPPAnKsYnomK9Lo8HpHdnDdyy4iZGulhzfJtbj0/IloTmj79GQblnHo7TOjkOjjSfU5E4+Sd4rfaQgjKF3d83IJDxbhpJsOswnFDfXfSy0TCK91fIdr48IjE7YRExVNq6Sv5YSEOj3TEkrRFybLMzCvOeg5nYBuktBkuPLl8QmQsfn6AAED3yYd7KhyTRj4gUACX18f7u03T9LCt/kkoPm4fK4DH2dMB7Er/yTDQQb/VpxF+kJ8ufH7p1pkD3jybGJi8dAk2LSWzuPt8v/xq1wJOs9hXeOL+1gkOF/uvE3bivk0w3hCeuSmUHZIBUAjlIYQJuAkVnyBHXujX24O7hPhhaO27T25G+uzDGTQwnv5JuXFnhYYsXKlhVjMlE47zeYLFmMNl5ICvQ9bEIM10XElgUe0Hb4ciORl2hIw2aukywFjc8Nu3J8FIV0k0Qd3vT3/6TLgGgpOoyUxBRuAjpF3fF2Pr82b4zES0M855vfELSCNxjPpDgUdr6T9J9wbKs9vVaTupr8MvNn/qOnP1EMAfPHAOJds3T/GrhTWOebbC7VEZb39oTkq/jQQqF301mitzbFImjiQB+Rwnm3JBM+B3M9sLPQfqaBkXoMpr1Su6wunz7Gcmk8hiznzSjKbwGIMQH+0iXNNsAhiWN8uUmaVNO4l0ShhBqPTnZYtt8X/o7eN+b8GKempTqhVNcWpkr9hhtV4BGuwG+/ZPluMqLQECttVtOn8z+3aFq9+OWkp0BvuCj5GmHSkYM80qRe9XyUxkmgfWO9FU16vqYhIo+R60scsQ1gusIL8hu2zAULi5e/CTBB6AAg530gPX+Vi0Ef8P96BOA9x+uWoAOIfjqL/VG6F5O+9msnuP+9C9/In5pf85Rr2s+/yH9/SH9/SH9/SH9/SH9/TNuI4N+bvf5T95G9jfX/veU/qou8uU7bCzol/TXMKvOp1D4gSsdefWqL8C6H95aE9W6k5765++S/h5mJpyGEzX6Bfdawz7juMePNBc+c0UcdOlI+PiJuSP+VRmi8I9Kf//w+P986Y9tQ0fA9V5DVf9Zi/hz2xzz69apsNFb1ZHR6Efi4vVW8wUs/PxfI/1hke/VGiJDOvcj/f3cwmehuvjkfSerovrBleP1D7lCwsZFNcf9u2+R0nntf4D0R2yN0sQ/nC6Afn+L1JGeqCR9iY3IkRBMNlr41I4+QpcSijLRVoFqf+WRM+/eYgARVBiJgGAx1DiDsRcl0itG1j4mUx5hqhxCHQpPUWaGhaUa1uEXWeYaUQplUQn1Pg45y7andklNKt+RpKeHad6+FMqSOIvu3Zzfxg2TNk3uRBDt03dDwHu5Ddrz9Pz7esEEg6ZsPa9jjLnbiInGdIY0+/AYpmaYWGB/KIotMPzxMPFyXFoFkK0XgFkBkDShcsEmzXBGPQEooymKj8OcHYHUdjMpI0v9yLmQDLF2xVBvdD2e1kTK8rKb0QaLxRBroNjjD92OwocCp3VMJooJu+j28OYN5TuRlbhQjfdF0prT+GYrOd+llPY5C4uTzVUMxNzcl/EtjsHM/kTZPGhNa+1m9qe9UNQbt8ti8zTJYy/OAmkdAz9WadYXsJS7MOzHzRUtxt7yMMhQ7S4UAzvF6ALgaWLwUty7JVjOl/80qKZOwPTB7IpTdY+Ri4hChBaNXGsepWPxB8ydl9LKXri7Cbzcnp8VFGzBfNgTz/G1QvDb1+JM+DsU8a26LxZy6uH13h/DxiJByoRaK8y7EKzpdCV7S+bFrjKhdTrdVto3qAmW1cNF+R5lOWbeoCDUV/WJIFJa7WgpEaSi7UqkJbrOQiNsuwkhfl4XfqvaNxna23Iv+SkI7qcqvsVIk1jQs4ChFRjEpbJUD+SeHzNs3JI4w4dVBVZX83ROJyXZfHhgE96Eu/tYZ/W1U8i8bdos8LRRIYBD5c6wtunECg+M8XK+2derdYYtMMk0KRrYa8LaysDu9jz0UM5IkBMoQBRkPKYhuw2OA2mixaCjrQWZkDCr6OmPAmBuCSoVZzSgIoqaqlV8c3GOSEI5RykvxWY7VZA9KGsBDbNOwXB2Y/+6LyhNAJ0pCyktwhKyLPP71UF/iEB3VNomSlS0C8zX7l+y8c4o/46TB2xTR3/K7hPp7Yx7dzxSjXpng1zWdf3GTG+94besnSKUVyjNaUr5dQq+uEtUfgWOzwDl2ykkP0gSy1N6AAqqp5HwFnBTMIdeEicqBpEkk9A7jSBC4adSVERzGy7NutInuU0Syac0n9mKng3MSe95eFwMHLRH0HK+tGiaEGXZUlFLV42x5xHygV6xhsNNToh2zjiVTKHIregJ6NOqVYzzXgDKz7V+AHYVvNE74uVdwxTNthqgzdrOwRLcwkhPz8p4DDNVPDPIszccx5VgEMLJuoBjn74XvFB+cvuYpUOM6/6yg/J1cAyeU3yM0nOoY+Yh2Fj1Dg3ZKx/OJ+lzuNM+jk78KCW3YKtcEUir9ZZfYYRJjNYQb7BI4Xmv46ftTXLUZHbT8Ql3FTzBZjjspuAfFeJp6eBdo8OI97ydpIjRDBB0Uak+XIkxTe9V7skiOLmaV7Fp6J3uNVYL873kcWzX9n7t2sA0t/ux6W5Gim+qmIL7Wsn0p5HPKmr05xsx4Xmo4yFY3rUdf6VhmS+lRhF1MZ37LWoGbUJAUsxXIlH+CyHrlilf8UBh1zGj1koYGI5erCxIffvp9RklPywWtO3WzR3w2kMfrpMnvSjL5O5J8N1hcD1fvrHjAIbvFyIvRdRywmtFe7fWp4uqiq6cOe0l+H4K0daIcA6uEr6rSdqbEVgBJmZC4gQhig96KxJirXkNzij5PT4Fn6YSieuGN5m/9JeCbdeBOB7dkDgtjK3bFklixwOi9zZtfxp/XuYXQPYgeHUyAxDLlbLL6/SinQPN5lxHtDd7s3qvES2qezHn7/QBWi3h9VygKu6TKM+wzA7k7KqSr33+lgT4xe0HGPa804BbRkSrDcgZPCtxIm+QRpeyZ5cEA4CKY/GpJB/paTCaB3uNOYsAiuCHIJaVjYNd5old2dTiSfrMfu+qhESEA2NrhTCqctIXxMcBzPdm8XqWJlN4yrCjLLTuBHj0E/ZtJSEp5p02cNOo3t4mPc1R9kYgqbvQ5elNI6Von1wR7KDLHYkVWy+NZYW37XejHKnzYtzplVP0Ca/3+2m571Z/e4X/vDloFGRuPu752HO58mlu+7KqBGyxCFvy6bNo0GIbgRsP33sGNvZUhCEUuIGAWQLSppHg9ATvPhUy5QBBdF+U6+QO/gKuoqHjfKQO8ya3fUY7PEsZTPVh+H7WujjafurcInwnVlDGGiv1Nt4UlpaqL8/dSxpTk4qiEtZNb/lTsqMI1K5J2AkOuwFwQ0ENrOd1dm4ruy4dZNQl8GNoIbOgc4UmtYa8chZgTGItAKV1ctxLMGB4CmmcHUu/81i+lwlnir9mBvTjkt9i2EcQ7b2yrpdVL4AH21sWC3a8aiipahTQBYTejKnyy7f/zvICguPD+bnZEl85wF0mbsTqIHuk2W8ZYEYf7H2bRKNHM/8V8h+lhKA/LSKHHzvpiVne5nrfM0DdEiyLuXL7NttbcMy1ZvUXYia1MGTBNQqlVlXsTabxnOVN3zavJY7d2094pkyMKhHlfB2K00zs8hQmA89V+8GIjLhPwhDZxPFXRE2+9oysdjqx3mckJwTyWCkH4La+JkXMApgNv2/dnE3am4Km5RrD321fk4wPDZrDRze7SZGoL0eQ2Mm14PgkWeOs5NQbyHOI54rrYPGbBCklUSgJfLI3BIklAs6ugSD+Ac+k8opRuDnGWisLoJmiNOnrtYPsVp0n+2j3nzshJKo5Qd1tQv74hrqBYDLmRwVBbz1WY7iCgmsZMhzL+ozIbGsnIYXUnPgmX4x5R8iw4iZGr2vliISUZxTpCRmd3pDIw2fFeqadIQzDrV8A5Lw6MJy4qEUleD/0j0M0G9gvkkd3jQ2pcSfohNVVaom+TyIoeajrslz5vscMuOc0xQrtjoCLdi9fXA2gmHfjYJhSbtJrV9/BYSw14k6sk4skLNPzwAyr3kZVHKx9FgY1pXpF/SpCEE3RMxSEGAzIsEILwZ6LdOnxKYMRGDeLKyDhxllnHCQfS7hVsNbigmNPMVXRJ3PH3mxXNRbHEJ7EEKlnr6mYNQOA98lHizTNSB0gm3x59ZMOk1fh7HpDrwdTPiRUuuI6EL+YS8fxU6reFOpIlCHG9BPj153K5VgFTJwkTTRqamD3SAWAua+dRKUf3uKHxZg3R3QXeYICw0MHhq5UE/qjw8MHhtwLvDFyGJ+kRqt+JsvR572e9DerobAtY5UOOoF7X/rsWAnvA8QNFeSbbt2ItqLOJJVK8NB9+MaIJIbv7Sm19gn1VzcAP1o45AaQIiDxN+6wOrW6kivZ4LMqPFojmcColzpgfc170LL0iqS79qg/lIDg8E3l1UQRGtTbKJAFiqAEtNhaPps+fCrYnwCoCl7d5QsWncQkfRGIg+DZPEPzRPYsH54T3ahpDtbRFwhsfyOgDl2S9IuhvDx86U7baXKld3wKRDMH7uH1nbX2unLaB2B30d/zFCe93g78U8zNE9tT+9MffeSwkkgTwQGTy9tCMl0k4+GbxwIcXBkf7S+KcikPoyklBF1MXh6X5poLt4Ssq0GNZmlwQPyn7F1yxmAXx3iouMz9JSGTbvroGK7fI4EtmG5N0sCyJW7xyTqegHmTx4nm10+t0nDUh7TosGhdTmByD5rYv+e+3mrSRwfNYZQ5f/iBQAvNdypV+WWIl7Jf3lKExQuhNrDID9DPeh+m4apYXI0CJIbrmXglqH0fmWtFOC1wNnwPNkj/KmOcL3pYjl9Qi9yxHD91azJv2f0wTz9oWZm1MHJjwd8qbK41f1IBXQOOf/Pga4XVHjFrjrl9JHp4YtprV1pb85rxDMesYg9sNIQgx/zxKRJA2ZpwZVjlL1KE5CB39xh/OGryTorACHBXPL9ks5+sfa5xJhKQ0y6NAq/kiZpP22Ku0WR/MBY1m2Siv/mN2qsJ2EhvSgMTO8VK9Dmscon6uXAA/QYEOQiLqTaJlxAgRG3FwxwMwvw6Mijn+hynJCqSov8aR617GAkNh6yzbZjUNakLuLJdqxyBhTM+xAjrufPE0G4SlZ51RBtpZjbnrTmhLNFLPhnuO2rB53Uri/A0b5OhLk+LwO7K6fLj+107eKFCjuPtRFfPOiz321xsr+PLpYrvjX7yJFSF7m+iHnqG3Gp99PYVKT6eahoentirCEAZi5tlHhVqkYlXwZb9YS1bR42JA+WTi+a4qU9fhM7hMVNXYAgJZGV/3cPZXIJoaY4YkGiHDS3DKGZpeIBgoxkJvI7pldgeDqOGjWh9LDg7brCXkUx7ARoTWtw38qpSRM1BwD+9F4CTbrrxzhsvCBCNX45a9C4CbtEmaHYYGLP5JDaoouh8p11826mihc2p7XO8pisvuMw73ZcwSGQ5IL4zoFpa/fQax7FewFllqVyY2fk0hFn2Nal6m3mx553GkIqYsL55EovjGtTZR581yjHzqXa/CkKd12u1OgwXeNJVi6SAdMFYVMw1DmBzbVfWnl7WOBFj627yIcRD3K/TRuXOC7H0jAC34YgYJtRpu+uNpZ/tXAIU5iHeH8bzNvi0vW8Gqk/nwr9f7aubi1l1b49Oi8zyD3CP8PLm4uTVsGqfTD7xtJAiMNsDGhXJhGNvobdY1jqepodHx3pODcHij1Fg3PebttRIMsC5RyOVoNfWz8n4jgEzoMwzFAFakk3M8/8dmQ/7JfPJw7LG5Rz3fwh9fwh9fwh9fwh9fwh9/wyhDzY+/2mh72+u/e8p9IVX1LyaiC8x1alazRHWyBegqP75HccWUX35iHgNNngZi/j2DP8uoW9qf0S28HZR/YKQqPn5PTyl10V3NcQQDX/Gvi1M//ltyCa8fxN7/hGh7x8f/58u9PXWj4jX6E6Kqk7U//odzj6Eog+ERU1WP3ZFdb5EtJtBnnX+ElD/LxH6HloZniFiYQb37JUXTtX3qt/ucXTxn98hfWxx6055GaKFa77w9wt9Tvs/Qehb1BfBPzXciYS/CH1wlodH66EDuA+Z53nUvdAYXFM9t7kHlq0PjzxuVpTfWah3sszIo1KrbdrLDc+UNWszoxtbltAu7cUomsF8bNU62Jkv7dQq7VpmlJi8EaAtGQTr9TpBkXnIDfJLzoEHAoQynI70kBMpC+j0WjocgKCFRIkBLb4g+d2Ded+Ocd/B80I0zLIKZG94NzCM9XsJzPuuTTaUv1SCDrtiC6dcyg/BtQSG443NksRtxXnkbgLZAvKUjj13xSsKcDIfnXgRYhfa4gk5VQkblKn9eFg612DIJzb74+FD5dM+ayWhiTsUeJbm94vHGAdTslD6iwDz27ElHfPZBxJZVV6qK0+bG53IraxHX8WBKMmbeagd93SdGi5TGYTUTxdkJ+M5D0p0TiXBzJfFYLxzueIEK/sH5aEv+6KYCaazLWXsxXffbhL4p9/Gwam/96UYCyV7GoCFZf1DGEF3KxNGHRht8pwFJgegeZvfzyfZg8ScypBZ3KNzsCxCEhzhYyQFFMhodI9SYk0IUTZlgRZNUAOwdwE+KKdJQDqF0oMIJ5v5wA5SZ/sxQWuXloehkLm+ce1DA+ANfqkD+DbMZzy6TfRW23ryw4w6TgwfDziNRDHOHt8jw/fuQO4DI707cm91oBu3WFIueB8bQ3DZ2/7kOWNpinKtrZZKKpk91BLHObCNNFLnWlzA2ypMYJgNVNy9bPIpLK5HRe9UejK7Z5k1wSLox8G8G+drbUior32jna4Ln7VqMuxpmunrrZFDxG2ZGgWGIBfUW5pv6JtfWhdz7Q3JT4+RKCn9frEy4lfpPebkgJtRcOSAW87a3rVj5sISHcL+8SYg6+W4QDKr7dMIezex1tY7rRs9Jp0ophpiPwJqvt5f1xJdJ+ivE1hJHfHxqlwrRWAFfOhu+Wm/F20gBe/oA0yNjCG51wytCv6YdkpPmy7JTUSClsryPiA8DQtMhR7QWZJR6B911Pdm1dFIdgU3NxulBQsjJA7oGAz8TWX21TZvymmvZKPoU0M35/Aw4QaQmc8LgxoLNyHC0HN5EOfE2GSJ4mlf5g4gntSnBWKgF/PSuikkfz/u+8NsgsCKw2wN6UTKdPe1XyvCjfT3LSQ8SnE/94qxzcVZF892zAGPtxm30m2X9Bn6BAoPNCiKmwSNlfMui/y9o529xzLL2ZtigRqV6Fz9GkqIp4tMWdGbPQI74GLzSRAkdPzs3+tXet9TgH874Yj6wHh8T4bhDWJLbQHN6/VIkW2I+MqxYw3cSDLpiq8fjTX0fkEyWaIz64O0AS0go7MMO0ic1X9hVftojQPoEGPm3ky6jIilqNiLOT9TUVc+kSxCDtwA3gRqxRzMmQ0zfUAM+PBttpcAvpuPSPIK4pPWuzleZQK0ekR4cJe73/Y1ggGUr/myIVjdYfnstv+bvffWkpjX1gMfiAG9C+m9Z9FlZNHbojdPL/bRBBotBfdo1lxpSX/QHVSTaADc+ExtcCM5ikAvbTz8MA5b5VH6g4+f4Yx4FAa4RNw9V44endJJvq5NQlGrxczcyLNRsKyDDzBWS6uH+fpmvmBjxudMRo6WFs85ndtVuj9XZrUharYLYmW4F1eYtpI7ZlBXi9Bpea/yG79Ji+wVKeA81CZOFMV1cUyp128CP0FQAVYbUobx6mqkC//qOdgnfAlFHJvpesB15YGTb8gd3A43zsd7udJXm5btu0VDNhvAvqGHY1VHgPEKA3YafZvCt3TPAB9aAVmMr8VAXTYNN/Yd4ZPY2asXkBHLFxlH5eAUe4KenvJSb34xg2QXimmVdzC3yimdfpQOw+wXW/UQw3wZQhDkfiD+CtOFeKrKOaNFgZc+KKJP97dMBW0iwJ8uw08JH7V1+3p3FIaGnH0tOrYlmUW0+cOHvS9r6bQjgi8x0+ZqCUIucuTaOYsukFsFiqKv1gFREFtFlLNCBDOKN89RUWxlKCbV2ydfqUGdUEhc+GLI5zdgmlv5ERE+hWKzRxT2Jbyl+UMLb2ciCsvOsKFDoj1DEIWYOOqKgMRchdLm+B2FP8UmtnFlUvgImmmYoMaueL0kwzQ0v5AEoS8SGEjEt5aonUjAzA24obce4GIjgBA3x7XBvaQ38fckFZ2A6TQD4lfSR2w99/Z5+vk3rckh/Aww3Pq1VcmbDY5g181zgv159bVm9KPRtaPgBpS5jjwSjahVQZiemNDBLRFItXpg8RbgRQ8Fe/0Y3X0Qj6Bermz8py/dAbTcmzKWBbE7eipMeI1oMEWfFv/mDp72PYF4WzgzvPK9KwkS5liTkdF6PJ/ODT0luQMPKpcHZ5zfX5uNC9phmfKQlosPWs0oTsRHxkpk/lLI7fROjA43lP3i8MWDECl7INy8uPhBMPDl0j0JnU+PgEG9NhEYtAUA8uBwcLOdDZfn1etHFG4r9A1Ux2VJM+bikeO1+RKkNRLtlcFEhXA15w4qD8YEvHxvwXu21pbcr82Ism6Nu5UjxEjDmNjtdEKSV5XLWMCYVwxbaQ6kYVDe6+/ZGxuWQPvxEo3NrF7/msJ9mXXoSR6F5FNAoeooC+H+YO2rqPe5uUrl4wEpFwLGDq2yIDCUlmGK3ndbENS0FG50vGuLHhugJjXWnXUueaEznjwk8PjNmnVVmNY9AcFmzVZAEP1tgUqXPH41XvX0eNc8R+kfWg4gtKkolisv2ae2oq1A+g4zhhMc0zCq0JJMWL6Yfg6xZropiWakta2alPy2mjjVYL8ZvpHUrVIE/2L4OI7INBIE/WA5iRFFrQchK8pQHvOilGgDEQT9kGKCMaZNxV+hW9Xtwxv7gWymvbCLdH6G58Z4xmpQ14N2k6AvdaTM016sVeslsoBxqIf7jljnBwoWCr6Zy+05V5vSrYXO6+1HhZ1mKH3RS9MCwDD7PpM0lez40+5yDHT670pNk5jeT3Ww+cmsT81ZgHrOfDTnqt7jL/mWpf9tKpAbdAuzMr6ITjGAyiRbcIKE6tc5casILzmBqdZh8OFNMw7P7B+bARK0cttTEGhHSpUmACxtg8d9SIYMaeR5Ad570LSPTtetrKCgEIgeOen+uFiv08nf13vvU3qf53P1bQT8oL2jGlruJc5gSUPoydPlSIdQwTAVGPzEpl9M2PROdLNSYaVNwxZrssOclrG/RAcsiCceUkKeGKpLaZGxkCM3It7TdvbbCugY3YqQTh2Zlmf7I3d9qF1MOutXzuttWEvYpAGewsTvJDt4HNk5f+OV+zR9rExAfTR7YyEMhe+FMpYVHI8Jva27Szspiqvg/4N5tl4vWQxRyWV00/lOXadJDuyxDiiSZVbSuZV8TLBObwiUME45xYM+Uw0pFvii/YrqqUKEvUFV4jV24BTSf5lYSVRW1yemlFdpE9BlljCVgeHR14MDlQPkgBlfjjN6RNzCTZpcI87zchbX8GscL72fNHIrjPA29mDsYzuJ+sHmzxbToXRy+CMMv/H7LQg1Ln+2tQPcoQBxThK3nMc318XAYyCTwrbn9GI/Z5C2xg9N4rmqbXFF3+lGsIYgr14PE9lWEE2TztgjGp3g4gtwnsluEUe/b+tPW5/NI7G0ry9TXptmxE3SnFmCWlzH47C50CwQyjTnY+opvjhvQQcExcjDr6As9PfZRBwJBF44y3ztYqG4ZhLPOg6xmSAK0PqH8K/ZR/zQsEue/WHmE2zYssEqVxXwr1hLiCJzHV03gZ2EE906SXCKsCNe5yBZMR66sWAPLJ47MUXgtdK4ulUVMlNv8zxgnqRzT7PX33U2g9vlOBx8+0ZdeFAKBwM53dV2RxJ903CrHBhpth/88/9Qxzn4NogvltPkB2buD1WaQGmbbp+Yg+cJfL8Nm6vOQ3YB1VUOfexWX43aMk2/4VWRzx7LOyOroWCu3OvX16zp7e3wsUPWF9qPLX1YC5he6w2v3nhP5++1h3IYKpIsonByOGIKPMyOrMupsv2j2kdgYAl7fW5SMbtWGTnkHXJzjAnA0SkEyON19VbImih+dwG+/GLsJR63TkFYG27e+TYP003DlPWfYlkxDTpAW04puguWonNygYiScARoScRYV8ifWn2RiPq61iQX/s9bzFow7s8XcPC2ZUPS+n4FwZNC0+qXrJhmTP5GWxaN673fJg8s8MCXCx3hxyckXa4XpS2isTyF9ka0X2eaGM8+8nv4k5shEV0RYrLgYwpQOYqsBsal5dZHXDdcLM+MCZx4UhtkHtXRjaDRwL0d9vK85BjuJKiHCGljBWComV8PLMLnN8TbqL8OXuFQAkwyMgHseDmznKtf6XqFL6r4eX58eWeaX8nTJa4gv/xkf6BvsRlortTRk0va6V+Ake0IjHr5c4lUnIPALBYZvIdv0EWBJZ8tj4UJ2ddhUdBfJrFewTLCguPuMlnQH1PiL0cN7SPKZcL+ZUcYlvvELHpCMRzDeylUhjlQuGToJ0XLiy0gMSDvbenae5X8W8E9Yrs7cr30mwL04+YOi5MXgT3bK1gqqGj2Y9ktG0btAR6Oc8GhEBvLZL2S+TTZW/PoQ4g4fJq1nBxuH5JWqdW51ZpyaSB6j39RDIJc7oZ1KUnKPk4JuBDjklUEZcxy4Fr5sQWATZzcgA6VjH7o1edkf1p6Cltro/XM6vz69di2vkqNgHO0p7XOllf16hKFv6/VMDHTKRJ2At5yE2U4AHKEQXgYfitX6RXn/lHuHv2RiAuxisuczMBURfmy5w940YrzeML5IXFVQvGM+FHa2xphrG/I4hi/qPXOWnjNaM0g8q176jFKDu4RVzdN01E3uoab7D0Bx8OsH+rB3mcKPVsaUI+9dTt5KlHHAw21nf1r4elHiZOXGCm+fsmJrROGTR9PWoqM+5Ki01KbX9rlHDv4uWhwInZ1mKilqrhxARgAcygUSkup3FxfnXBizhZw0eP6W7X3iUUNCz7UbqsnWC3Lmli/gdH8XtmG+YmB0ptFkOV9G9wd7dkUdIxQ6LPm608qtJUSUPI2jHgDlsB4BM7vZyrTImIn/z0aTxl/H5HOd5UoX+ipF1IlOguo+dkv2uX18QQxfV4FF8rRFWmhv+OGamq7j/bsh4O4zRU+7q2I6kkO/g3lCQS8OHEnWlZlvFTiZ3+03IRcC3gvOlXBDC3qpY/CmyqB3M8jxl27t4nLcQ77QuujBZEPQfJ4Ii2ZbVTth9RLAl+HmTJGYOLZBYwYXX4sqbOr2bH118tpA2Z/LDZr513h9ObEmRzkI7YD71OGP8Bhgs32idFyu+ChFZW7HX5nLv2k0hf12WYqK0PaPPwg0y/EQjWbE6UrOHXdbDuWvY147f/sNR1DfNEtuC3wE0ZCv2ftElWjs9LTK9LjnYQhxmVvZsbx33B31UcMe+ZwDUJz2MMRGg6ocmY0uVsoUw6czImRvcRCzaT+jSU8ipbeCsi5m0B4BJHo1MdL1XAEPd4UUYT40yz3c36h7MEa38qo6omyKXVd7leD6scm9yn7IuPSRgGwI3fV51wCkN8tSQ8yxiWDnAEEIsBP/Ln/1oMj479Xn8BiqQsYaqJsKOFDz9OQOmYS5s+h2JwAPVsDP7RAEAdUY9AaKsCV+w7PLiAcMOwlD4Fl77CHvllD9OV1mouWxe3DXZl8KmqryyaZQINpBY2xOI1EuDa1WExKStrHHJ+VRuggTyj8DZsx6+HvbaCbFcpd+byK2xLd7NFiUVZ30IIooDs/NXji5mSEr94uIVUplxyhgq+L8RVjqyl036FLz3ZYNV1j8YYWzhRy9Vc1RnuYk7joMhNVItn39uZHmGkhVO2y4Y9FeiBU1xyDYf9KbcXUUiZLYhiM4HSJUCmeskxF9u2i1jowQulo5EPolyswLyRt4pf9Am3pSnDDxv4XdtCBpDavEKGs+cH9/NwduFniS4P1DrxkaSy/9nNJAtF5BZGKyCDYB5nZn6NhFDhLFNCfg5Pv0ScdT2iQDhkYziAEBPKiaU/7ommFwjxEUWhNEMUmKtyvp6cDwYvWwpLSrceEUIhDPZNbppdAJlrptt4x4kkZDJQEtHR75IIZiVnYfyPBJez46mVsIgEvcKPymrB7s33sNdP4IuXzPQuIkZGmHo89vdwWYCAg8HvJcc/Ww6NCGPl59/Ty5xeWWi26r7LB2hk7OMxADPX3QVM0JvAf//FLXzGCQEwO2uA+00xBgYb+ZPFCVmOaDV+GVFxfKOwuwzhuvjPVpl/t7Coa+U1qROcbQa3IMf7awP65mPfyzFkvBefqqbkGCE4JZz0Vj6vSirAuTYJxFTN2c/hV5fBnsTCFi1+TrqfAM4aXNaLirrkfugtot9J7DpTXzSjciA2nmqK13f9qel9+6upMvu4Vrhq5U9pkRCLWbR87YeaFjWc+0SgqaOL0ATjJZp+0WA10Eb5pC+P8baTqNxzgkzR8rfLiG1otSkQrW2hsXjCJcd5WnGhd+QFVefsPLjLpppWMHO0EeWUg4T33z+QW1FHFWol7VP2dlnyl8S9h+guGMYXhGVhALxYHB9yd9iiUVrR0LzFmLrWOuKO3dfaZlB3U9e9PF3ub8rlIx2JnGOpgKNAi1R0pwq3glV4npj5k7zD2KUNharoFBagXYGYrGt75XZhZKXbqIXqv7tefJKN+S4SkDtuo3bGN85IvOmq82GAMPmntybNsOywSoTaU9SIH8ZRy9MYp3uGmyaYXB/Ws9r7iB76bJCpZZOEzjOMsuDha+N3e8n4cdrFGiPQuvLM2vsnztKKID182YialHi1AECJWhbCXzsDPDQmbxx9lfJygKfc/hCy1tHf+tWHD+wSWq+FcrCh/Nb2Rf234EdNvkU1T989+n3/2+/yz3+ef/T7/7Pf5/3+/Tztd5v/sfp//7t7/Pff7mLUhmW3CJ7UeqoPJf7a/MynjBn7X5rseQ7U3HgU2+Op9Th/Y+o+92H8ZT1+bT98bHtyZrdvo/gtYvLHFvnAlDdy/GveMH7aNnxg1fOffrun977b/v6Cm92OFAmqFn3cOHcSUlM0IBci44drw/womfDDj7d/f3Jvt9zL/D6rpHfvvvCMOEntwk7QOrIdJ+zf+2K9u4+8z37hNn8GMIehNv/sP7vd5f/zP/w37fUJyjd2/jELx35x9mmJXF7gSMwPzFwDmgiV57WmI6VS0imUBVaoDoSIUVaog1Qbr2qk01YYc07O58lMYIK6UrIspqqsMqvqbGc4XWeH8XMQFqm6PLc6n/sA/hE3yISH3kbSs/AOEdtHi5A9BzdL20XIBYPIhYH9FI3sFls8VbMfhhikvjWBAEXh71k/DeFrHKAL3+XQCK3/JuhdEgYEYtTm/3GlUnfeD9kkYgGeYD0CyrYYQ88ooSuwYs/CVaaytuHgzIJ3wmljmdaouS2o6z779tQX2FApmToNRztiLvJWGOH2L+XCNx6P6s10f6gd8GiiOWTUCatLendeSdh0aRuO4hVFGLhRlG/cqWK/ROZW/ysNa8X1U2xtDhsxWfXmYMRBL0Ym2ufrJgJu6BLY/JCcF0mBuAXHLhpDKBmOuS8fV7SkacyMRRzhRgdZ+FWJnLxV0NXhf185mrqTOg+VjgLXZtZ1m7K1LeZfYf4DOD6zeDxOve2UfF5O62UHQ+mF+viNdH62pzzA5KR2qu4ZOFeyLQgGdZIUz+p9jE+qj0G6cW7tSGBPa/ZhcTXnJQ7LVnAeCCUf5iPRS5zpj5Krk2fWlOCR04LDT98ZMHY8EAQjCjkqcA5lKz/KsKWqWfUaDug4+ljN1r1EqD/5lXSfKapbNc6U7vEJAc+ldv18x9vN+BV3L8WZqc91ZYBKi8AGkGYmKEkV2aGAvaQSJ84pBhdoffI4Y1ehd6ypTqTZK0WNxmX2VIlqRhgXgA4maN1YQ+vVfGu9phmx23VGRf0XTdzFPCniWXzOGoZxHD1TaN/RkJtQ1fqwuusxhqfHPlTOHWx5cbBbjyGP3JUQycqQtdIdSKVNTZVU1EJM25FFmuG+UmxA090uoEt/GL1v1qUCWianD/WAsEvfem+4oflAHGUkEj/B/xoF6MGyCEbekVzVY8KeJnE/7M97YV1Q6xTDU7PrzoAxGElIvQvKeB4JPmr3yiAN0pqEK9rcg3SGVyfCJD2CqpjgRcSZilwAXmEr/bvzJGE5T3R8y2TVZibsA87F4Q7Vnd5y8SVIw3YOuqx5v2KLRl9A/dyALFrqBP2XYeg2UXzHLilHNAifhq8yzBwgZ6U6vg3pHbFjDNaE8Fl+XK0JflKLq8cdPtGyubQ07eARDJouL/g0y5LHUUKsSN42tYqiycmtLrWo2dvyYDa59HEL9KhHt7U98br+4fw2SQuQDgWctIrhYarKItWTGsWavsws+rZ8qRPuhHF0EnEiTftXaZmBOwjj4dsEhP3P3tL0f6QyrDK54f2f+pVmkQtqMCt2sguo2PL90QDSUMkX9pbbQTG85imjObCIAex2JtVYB4s+h58yh+fBcqcj3odPrsZCiIgsHuiV37hlcgs3hnLBgsPiGrbNwCKnRBl2kUPhevabnniN6JgS/Mlbyh6oQ4qEEVxVoH0dkd3JeC4moGmCLZPcayyeOa9UF3gjffquhQoWbf27bezXMhhKIS8bXx/wMB31/mVBEosxqbk6Tj2oOdoEXIw6UKUwUXH1EynQHla4MwaCCPHdGySWLxoCgHSuoF7u/UX4yKmVuobDn0bmTPVNCodvTlf3sMGfBgXx5Uq+Pzalq0dCtbHh8WdCnb+w7gxzDVaYv4mMWIGtLvAuU7dCjpBqmJeKy0isp5H/SeEPoL5Cmms5YhemQF4/7CuH4LQIC6T6Y+nkmlHnpB7Kcju23b93sjYNm2zH53Cu8Ve+VjTCpit6K9pCrKR/mS2xgj6HROnshnrOJqiVHqkNobTTi61YJZfjN353gzt2kPPAFhVrpGw/NspeCAirOd8JDvz9sfEN28IHQQ1l1Uc625zL1AbZXWcBq38LfIECt/RNvtYaqdhdZu7OhOjz9YDgIOt/vRhvTlJlVHW6Bteerp/kvdV2BM/dpY2JGY+F+hY3tlXaCG8/WcIif3ayay/h0OsOwgso5bGqGmyciimfaTc+GrMfbAxbu8dz85of9dZIr1MIwxpNCnhP5C2ZmddP8ZviadD9XVuv13+qWXuZxFCOogXmtiU3L7VCydFHslNa3FLOMecbmO3w/UgrE96dgLZVAYa8ov71/fCCqNe81Tn4s1YzGVr4UsX382/HGnoajkK30oeFZ6bKyvWfeITsTHzzhZCFsLySCzkQbosk6pymnmCzirjN4wlyKK/zk/jkeUXQklZMmmC0/p/OZ3WKB/+s1tfKGrVR3m71i78MAOtrBYbQv0gcut1dR8o2qCU2BCg7HMDqdbND7Wa0VbFBZrSd6LGyXQPfGzBvb5Gpeiekga/SUwGMzaycQFI2A6QyRdDpBR3ObMjBETJ7I1C2Bn4TWsBPylgaj4YpcWUs+CFgcHSHdeGpmP4ufSmJsrlu7lQFMsrRdzp0oGEmf+6HISQjNzfE48HSlCesbjyTKKlz6BAA4LrOkbuLhinQGorWqzb5Hhz+ISIJXJZcO+4mXwfqhYkInJfJiTVD7W0fc7ePT7czfsJqWhjh/SA47UC0EwE3Vh6n28sdVH7LIFoTExdc1+eRNl79SGDj9krdlf9WTXBSjBcxvQxt8B9+fiq6bXN1x71lmufyi/MgJ+mW/dTVvMsJGrG5WjQQ2NPsWvK88SOhxZg5Biw+SSw6YJU3u9CRIBzaICjQsmJeJRPlL/NnaVlC5R4aRe3IsLFRMS4+SWg4GtY9KeeI6Okm/8H0ZAqhR2SI9zGW0BMkRjmArB9FrqcQN+Q5gRa2yr85NeuYlZAkSwxEMy5Pl6KxRd6Z98lNTf4YRYdxRAv06THpJLu1zHUUGKFHQMvayco6KgCazzZBdkZwQu8tpyfXkR0GRJ4MfE1mN7OWGNYStkcq5fGY3+LUUlJiYUCC0yU2bajiROeD/0GcHE2IiI+ohH7v16hov4XYl7fM1WWhnrnWjol3VqvGXqkroOsFXG/ar/SvRPRURV7VjlOUkdLN5m1+tQscJ63PkH5O6ZXnWrW406FCexKSLSxisWGAu1W1PFbl36N15PFZ9snC9AUu8y3m/VOymfqT9OcLvYRzZelk9DC37+FTUAQcTnA3BV/z8XOiHGeWPFwqKNiOq+qGyedA9xlfS2GNhPxL9SsGTfH8NLBn7cf0pkaLRvknE5xdyCcsvPI0aOYRgi/OrA48Z6Rcuu1hNq9A2tIn/EX/EEg+gUHyRpBpe3NY4x58e7mtb1C5vKn3UaPz5sC/Grrt/hASienQnJE46hMJTfMtPLjcy1cZShUHNvdoJPPlg96jpFf00Hg+SQaCKvEuGcEAPo0DrmwmgFIPHk2rJ4THvn1maR58QZRhEq6AeUH7+5agkYGlgstczyhxiamQtDZ1aPz9huE+jV+bfsa50Ww2g7kR8c5SElLftRVQ/CFpUZmcKwdhh1tPlL9obr4FTZ/Ak2yXomWdBg+Pvf5zsq6S4V69e410YHYVfP7971Z0ieEWsrsnWl3x3OlIBDHwkGrzT2IFF7BtUQdKPPJ4wAdOKqa3rHH6dDieSInMdzp28RAFNv1v5HtozEfjmffklp1jHT09+GTxi6mYuxURnMU+qf9/BKtVPUABOrxqn3p5pEBtFU17rbb1igmmcv/LCoj/0hFIAxNCnTw+3vg2DCfjeUFFuLBBw9z/KBaD/NRfQN9/unxK//2QC/skE/JMJ+CcT8J+SCTjN/9kSv//dvf9bZgIG5zLCD2L433d+lNNEjM3yFcj0IDzx3VoPYyiR3HcNVPAbY3XyH8sEwMbjQDGSNMbfm67DX0bh79vgeLNC5TRuCLN4Bo/DpDffebP4f7vE77/d/n9+JuDzmLzb/qtvfj3EL+79ZViSBsLjlnl0v8IMvq+T4Z17XsGM/2Pe/P11xt9pnq2Avv1812Le6n53/2WYrPDzVzp6MP/iSYoxM3zXUPgfLfH7/vDf/xsyAe035MiXw/Xz/1Xi9+pcNJIfKA/QfCtXNKU8YYcQsW8RFa7hn2BarMi1P2fyGze0OaZzD5UXma96ORTGhQBzMabdRdVr8bUXPRnxlZZt+J150GXGztXYho9vt1WxpEbPoW10ROdIXTdoNILAeSXrOCrCIR8SIqWzDS1QACw/EIyio2k/JPmDMzjMv6i4ZQ68J3QzoCAH2BYs6ozUGLlT1wqhmWIYBGyAbl0uOIbHNGrH5AsS+U4QKLU6UHhGgMa9Huv6audOXtkvRA5BCYxfN/5q0wVZSeg4TPOnjepJOJvXs93zpFUmw51s2sr8ClRfFla+gXIoLKV9Ac+kku/LBEAhTxEyGVlFs4iKbR5Nq7pPOaUpdizDiIKGFn1cncx2HcKH5bmv++1F0hJAg7l82ju+5TWor1o0NfA5dGoihjrHAmdrTra22KWFTG5VrlNYHd4A8kQLqeFZoMH+geqeXYiTM50ONnfJUh/kM+gMJ3zzSpv7i+PW09exw+zdiDAaDp80FjgMLEtfo5qBPZyILD2MON3JJg7AMycJ18I1MQ8plD3oZSQKaIT98srqjtSNiajZ37AdH1m78xaYp+SlYbUEJdGxhm+6fEGZrvNAEETgKC5Uh9sPntQAMbGuf/xYEtvY1LOG8W64XcgWCPtRY+utDdPKFC8skvX5rOVrAwFPlOx4kSHjAzh5D/e02Ea8WfzW6nQpnmIp/ycHXpiOXj5/aJVr9glLgiM+RIQZfjp33AMepYuhKkhLem6rgFi2VQtbRbDNVBJqm78JHmeSQTePQTL/yvgl3ueykueq/YtzDAVFnK7OhL5AH/n9NIHP1OYh7bHq6p9pSN+5aOeGAwAe6ihggvImDllzAITxAbqoS3QoES8faG6NtovjEqq6yQ6Nq0sb6PydRj6GoVHv2nx1GRtpNlwE4CDjh4D4d3361H0nLTcT+4I9g0dJFArXa8gLQg+qiTlgI0ZttGyH6Sqv6lo2cZMfj4PX3x9FAQaE4p3zcS/bccHMvh38tzpVZzcUYSEy1DmJbcxPIZoRHE71a5o3HtcQQuJMcc8DB3kieqYgSAqSZO/Ah1vRgGXX+QE/7afWE776qyLwgj6n2OYirDoNxx8IPf1jwH4YoY3LRxCg2rSDenGYICn9ZD98FoWBiXuX1r3jsazftnwMkwEiouduW0uLq97MzRRKlMZedwauND0AVXVKYAYYEq1wnc4ffbFuVeP+KGifcprcO341SRAiWzkq0fIA9FjtiijJMigFZpjFSZpA82r0Mj0G16LK6UKiD4oa7nglUXrtPQl0QEijFQ+aGlSNdLrrG06kchKt30UU0KQXtdv93XTo98KBet+CYOL7hP+2IgO2coPBUtSctQGshwu/LNNc2wHiMH+L6ajhQ624Z0kcfuiEmBLXejdQm98Xj1qs9lH156upjzBJQTvdGEGUFMv5Mh3Le8dn+JpvLCrrxHyCSHjC37OreSXoiR3GDZz0ykXRh3KoQneX1nyvMpkcHIAEvxToEF/lqBaK4wvvlRWk0liv2U2ySmClxx8oYcrkSlSGzYqX6xCJ9bgcjVCSf+fVeGTGYc8sfKWA0UbUdz2v/mQvPqfDkrQ0C00G8etinHyU6VcDIefDyCLv9le4CuM9jTVobR6kbu66JUS3mT21VdglyjJfoPSfZmYYRUdbdDl6nJ/acKQF0MaTOX/KV4cwDK/ZPOU7Y8U0X9wkUOrTzDqm3e+vI28tSGv4wMsthebczxtsq5d4VE1FnYrRdDbg60cFPcqnTmqkfWpWYidsPn9ZIktFey6x504MgsIwQht08AGHWW44Zi8SBDKCRMtRJK1Q3PX5qKIf5OODLvSDSta6wsBxL4Cm63a9Efu9Xd/Xz6mCyCEBw/TgR+9N+YCjpruORLHXDo6I/CZx9xch+aww8kdjUKyuR7XTI+wEKoXWdhrFMa3exsguZ3oBJxMEdfZ43mYy1mGY4PNthDmU31/9HpVZzn/Rja6MA/qe1+E/Tpl0LVt/Nrfkl6mKP9tnqp7pEh95ZSpOSXli9QMeP+AWWPzAZcc8cB2N0UQjqI+e4/X1r0oG5v0+aVNEpeqRqVOTotf1rwugJcM5mcYwxNNvQOMvsyLhSAnVwiddBpe7t6mAp757UZBl0a5Xg+llLo4XLfSlkJpQYrbiAqywCme5VlhIFyAN4pVWhJcNuXd9fIxGwmzKBMf4orL7OZJgpBzvyVzBde+lcj/+xYpKhtg7SK9l4qnQRLvO6DWSEAnJxzHirUbVEii0LS8j6EcA5zJRuEWjO30QaGqfHFPzNQlfvCvcLBRflcwYzU0KwLLNQ6NQgNnmJhIobQt/10bpqEboEAczLB7e+mheVNm3jgKg04kMPkGq3PiCCNAwoaMqOmiYTfZwOm5G/NXXnJtSBjxyAeGyvtcV+fa3Wf2Ed8mr6qF6MLxCwAyNM05Mo3JMm9YLBU38bt2mmvz7ToxVLNeFb+H98nNG2211UhM0zb6JizuP7uwRbzBJGpyflymoPCvLKEyjX0CG268NYHdg4DHdspvT6Z4R6Y6txfBHZjfiJZ9xJOp2SPbEqBdo7UBpqLL4vRJP4ieJ//KZaYT8TnyGkbuPEJGXqPsboKPVN8xY0GhhX7bvbhO1S1kDtUgeZBm1L/KAU2IUUvrx0ixUOmQEbxkT8uRxo1yjr2UmSeverNVQMdMrqhRPqVH4lwGHeIBSzkZwNy3fgYclZVYtypLyvKBsg8qgw8435uQqazwJ60wB2vgysVC8iBEp8NWQYACW0eK3bJ+wzogCOaFU4snuPoenKWGsagPFsueszAu7XYXeBhqaynkgP1qcQH5k2r1HVbu9SENLMuKERXLOQppiEU5Q/l7QRv7FZ+20FWhknp/fuuvXFfaLOfrpkhZIBAAEBXmSTH/KZ3z4fgVBap/hgTTinbbeyEYOmAW9UjJMEPFHlFwFIiCXMg/iqHp2MxQMmtRZcovk8M70UbfLpQE6II7jDO7SXQidsqHJe6uJFSsHITTNjWppFkyBA6X/6JyWn39dbx5LVgLgqq3LBwa4J7tdsxPr28qLhLO3FqySl22XatWjzxDVbPrlazWuiC/Q0k6nbdEyvBrwAcyUxquXvjK0OA/+WCiIi9S1asbFXcE2fFiwZl3Oiuo9SXgYqzK+LHCi09IM1z98g74KxnNS/KAXchA0iDaHpzBO1OLLA5dPejY3ZW9uw+avXf7shf40YzRMDS3NoEJQSxxGQPVLKehQMXz2O1HQ48N9xy4jQ/mxNx2LIfdry+7Ms9NGQ2C7sbTeaXu0I0Wml4WNYR/ouL0fEOBgSj7jOgG0QABo74NJymGDopT1p1/sFT7GeYovKM8UJ6MpVAt1jQD4lel38bUJGa62Kk0s4eDXWObW4HB4GECHkbAsiY/jU4L8zIoeGRCok3bDOVccV/JYzcZUn/I7ku6Y+TqS7SQQjPBAvIQL5UWmbXq2B2qDZ3qWe+j4aj00DJooI57ioH/UwqHg59llc4IOjPRs9DeByIb9tHRPomGnHXFctF9pPe2g+LZYdlgslpGFB2azFYWjal3Ra+k94vtoUjCFeSGyE+37dPJfH4E0l2lKMBZbedunwHy5YRfpMadTp+gpDX9dqZ64o1xuzmfxdL+Pjv3VxC30bGAmC+qRR7NqUJH08emqkFOkr1G6/jsrY3hdHzU2/d32+a1UnwNjapkqn1iJaRr2XyXAJo5sl5TACFybZFh2sOfynTs6RtbvaFn6JTOXBDzgotUxLC6uVLEVZBslU70PukD0n0cVNBOCOZz1R1lwjTT5gEsPBTo6FCxr3+pu805CiBAJEoKM/Np817CXpjLb+zvwU8oAE7FKgVfJFlJ5ytWfHWXkxzpXxw5sypHi4RaIu/IvKnJvcROGo1GcYdYHVLfcuGXU5fn1umMFvXOkW3AsUP89aPLlRFwcPp/p136DVVl/1vriMaZ3BANgBBIcOw9qq3f2gsgErhbYg9LwiQiz6Ge4WLcxmRabWGVpBkmuXseGlj4sPzjRgHeGkOgzPM4CfnV+FyO5jMx5UDi1+vyPMjjkvzI43hsI/+Rv/snf/JO/+Sd/80/+5j/liMb/D5Vbof/tK7cO6mCG8fX2DdVD51/HHBr+F3rHghmP2f1Vbo0RATZ8tbMk4V0Z/8H8TdvdZst2pgchsR/Dbzu4yceb5SfdXw7DfOfPkJLafILBbJl/P3/zb7b/vyB/c1u+ghiSA+v+24/2s8Vt95d7wc0//PG79z7nTAYBfecfMf6PeZPj1yRtMBih+3d8Zme8KkD33zHyymbxxpNwf5VbzZe8hDvh63devv/GEY3/N1RuxR4aUqC/yq0P9N9UbiWuIYCDEkChAkURBCJlx1lNfka48VeM3ypKBbt21E+t9LHTOBRTqJJ2XvG8iE6VOLr6zlkvQJIy1vy9AwoTT4RjbhxYFloNvSZaNGcOrtLoGJ8jp3Hgfh6UxC8cIo/IHhHwdaaovfuWToG/GU9xAIbHMkSi/TjyrHj9eOtiJLM7d/j09NLqS/B3Ilc4fR1nqt1R1Azx4jirAHJGBm7DURmOO4445L4WIZkdjZP+2SK9yoyaa5TwooOQONKOg1QJvLOoy+OguHe9BTrIxqxxuZlm1AD0hbkMx2MJZy5nXr3e1mHESq4+05/+lZgc4EwmtBf4kiX5XhfQc1tYc39A1wc0D/p0CKSsVX8JTlgHEuh1ZUI/8fnwVsrQJIlPbsoIjCLT7CHt3mJCI3V+j7a2XeF7BuOmOMTD4pxcBCiyIIzC6Ld4+LIoLg9aCUwZM38JZElzgcesJOF5ovmYnUy+H/iDu+75xU3EyW3K3CNHa0QhJorDgfFyzb9ErXDUUakJGFkEqdIOP6NebpHIkSf1cz7c39Fw/cda3DouRbM5Qumw97JfJDpJtYUtjUg/meJtdz3GjD4XJNoawULV4RfxZizTd08q6WVwwPVZapgO5Rnc6+yy+FiZDiy/qNCSSEEedavn2Dn4wC5xwBdxfKBfID7a9wtX1UZpGMBLDahiLy/frYBZ3Rda5ZYrF3RzUKJftgGL5Zi4psywxRY7L+6T77Vnoeei495VRTayDI+74S2m7bCPH0S9btMEKO2UXnQFc4gMp/wW/9YtN4Cm6X1pluG+ScvM/eD96wbqur1wnTKVnKHbooCXgOAbWbhUbOtLLPRIy06nMvztfXCp6+IHAcU5DZnR6jjQ/HxJEx16QbhAfnlVVXUu5Hbw9N7ypGEoXKj6zJfGGBcv6c9f+/KK2OADx8A3c9bzIUUP1Z3z5CXJZgQwrhjbc2CnlOBo1LVMjsKbW1jrrr8JvTjDSl9yc/s/Lk9NHWlYorX1l3pB2MONp347tdSE4s+23MXBFh2X1sGgpuRDtV2rSawLSWfIa0e+7azdvU2+f5N/b5ScDLuTmg8Td4x4TEPQqLZH9dA1slYcyvmgy+HQ+DcJf3g4VxXhwd/H0wtJ0JUP4tjm2lcIC3LviiGlj4wMs4OC9JyXjwXbikbt8TwC2Q631waZN2hdcaYkPYA+rEN4pY6HyC8BTQmTa/9Fu84GNDl3t0Z9GY+BOCa85dmwq+7AQCF1PQxDRa4AK4jLCWSHvai9DSsOVXIgiVsDf4ANoVjXIl3p2zoePeEMGg12tUyxAH0audPDVixz7r19FW0rVQajWGBPYov7ocRC0KwsrEl3y5ZPwV9hhsqW0EPBeLEJSSdXnt/m7JzNuoxZ601gNp2uH0KJiNH++JpfUji+bAc+FuptYvfyjFmhKi090hGXTYu0Kfk57qIs4dWTlbFQmtLZrzVq/RDZttyZAOdLPQUQu2a++dLtqCoAukEpAm/sH6KAuywZbtFczOleXaThr/OvEFOzdepfeUuY49TEKyr2G9CDC5CqvgXq1P5SDTWyPvIqmz0KUysMmuqqg3KtcBhsvg7i5YCVqfn9FZSrEFLV9ZLimPs7q9mTrYh9Ntc4qM69FjuQadEahxreseIvhr9mi0A/PcZA1yQo4KRQabxpXa7sZ01y+VPldnEOmxll1OSKZSonu4BC+CePGncONzhMdPtAOq/c2szBmpvFjzQN0FHe/krZKHTWWfLNLje+/qT655cEgQDZy1MvQM9hiRetinWgLqpFiLX+N0Lj0fnd8DrgxWDa0/k7yOInl/rgVUfL3plsVHUNshh1HSw/6G00lPPwjaOjlg0AsY3pF2gLVaT1J60WIMikwgfjU7Da76Noz4tJgpcCqOlZlXiwvUmB/EpLFegPIkyveQ7FnmF97LCBh/WPRDjjFAA5NRciFa9FFn0NlArFXaTS6vphiyb4Nz9X4m/+cS+b7nvgRcSSG4jUNg/mhfimFCHYHECKsqJHq4+OZJlEuJFZrJxChbVhuM4+Kdo+NSYSCjAXEPz8HZrD/Enhd4aFry2I6MWeK8ZHnbpuu5Z+9jZ5ncd4X6R9sifjvGAIzAwBF3u3gqr0LCTjRBBLzCftvDH9LAJC1XD7UI9w44DyY1ZIP5oEIzHTTe5MwODPlVp37yccL4DfW1+wMhh0ZGcxNsfqhwq8tc1sQkRsaGIVq8vD4eCLgRTAVpsw+Sz6x1lcjXABRHEMZtIWuIOEXJLhWnqUSbwABUoQWNVTSwqHlwHJmpgTuDbybvFm2aVKz5g0vE4//BYoUQ00n00t8V/sYYL2YkSkIOZF5daas1bxgJynvNrPrbOTHr6EMQKqIGlOxtvYeiXiSRnFTq0xMnebdI2+QKxYAVdwAW10oG2Zvv2dmtnI8hWRAnJFPFYTNlBOCQuNz57vfrs70H7J6/B5BCMrfUBg4Ja0Nu1YoC2MvevAyCX+ZWnXffASLYx2uWl38HEXzUDQufleCvAvdrsu4m2S7YB2JkmMX0XP5npXlw6pVojy+/lDjjFnyhlqKHON2TYwpXFwh0sAkACCdNIQbN/9RRbr4SX5GBFq/TKM8ni24Dzw8kGmkOZD8KAFBXr27a+Kqb8psetAxtyiR/CLeueSTSwQAO7rwLeCUWR6VXy789zLkZhy+EH0MX4aY9IeWVN4CkEerIW7ThSfYEcVZuWEW5x+ogTziGOQIh2OUux4pSznqxR2wS4In+040cZsc+mQ5LNsVRMaYjP9npyN1eEiWw8I42mAkxiezt8t/QAxdU2qR+wKROCQNifn7XFjP1OE5u5fNvEC++dtluS5NS33o4ujj6B6hbde9auwIJKESzfIdJwWNqKfth84hqvyYRltnod2tr8uub3x120On0V1yk1cyUuqUUA6jU6xI9sICBOs+YmUVh5L0/8hcHuydS6MasVJdukojBR9a5HTSC9/GRWNPw7z1D9BWa4GDRkvRDcTF5/PSwLxwcQLln5zLYL5Zw8LupuGRUKIbtqVwTEZIR3OamS882Qw6drJoXXSimesdhKYk2c4q4evaEsvTpFXTHGE9lLSl4/SlEZVggiaPcG728dnMAmQU5csu22NeNq/L6pJgGQKwbJ6Dd6a+u+3wNms6Fm49gzvDR1N6t/IY292EkSnPhOWY6JHqTgn98JXOTsv2DV/hcXaRnJMzpPtXNOTV0XbdR0TZtc4+O9ZdNF94sFu0y+Jg1CaKsKpcp8YazPLxMFgqCJjl6ya5wQVuNbrVdwBXgAFp0BxZhiYBFGNATWhITDTkCTXM2bQx3/4VxyXz3o2YkTPa2PLCFqbNqUE+R1l1pXcXVLc6+iA/kusCGOItsvn20WVuPQJZN7RGEwf8jsmjJ7GyNcgPGdoiJJcop+Kr5SpjmVGSovI/A78Vyii4xC+LBRCh9xNsLMqhJvjeI3DD/aLHGx9H3iTBsZDx991+zB4O/tyMeLouHrP16lZS5oD/nXbYZPa+rGOuVzWDsc9a/r2/eNUuunwxcvBgi2TqPtNBf6jiGi4dLpjcS5MkwJE3uQv0+sVqQEmvrf3uvt1VaP/NZue1LKnC+zAqTv57/0jjcjkWuUVGOBIUkdpxPgynR9pi82agvM+AQDvahimnanlVqfp3oswJVZKl0G9xAEvyCUb4cvZFm7kX/DjfraKZ+WvHE8nSVE5TX5m4xvxflfaOZ98i3OB7Pi/NPcdva7r6Jb/padCwwpWGvRAtoKVcwTeQJKVcw6/vrnPrfvuQXV1ddUbPPQGDOxtb1IU+fFba5lLJHSmZDKoQuh9PqZFJxKMfybRcdhBEU0Gnpkv9aW0NlHL6UlaPvtynNCADwI6unIobjw+FCBvd+asy5C/P+ajMG/iPoztHsMXIHAmHIbXU4OjE3t3ulog0IjU43cX2JPocJc5GG7Ju1klOQjZF/OSyeauMPWTuGjwWgQROg78uuIznpqHwJJTh70KGlLdlBIMo9S1ugByr/xa1GNPqQR6nRlLbejZ9GXcUYGvOYsUo0gfgM58ZjjoecxqPXt1AsZg0iRsQ5cygWB7q0G+rrFuCD9HQsIwCfkY/1Gen5AdQATbiRr7ZWE7wUy6GbKU5RPCZC1H4ZXkl9GW6tCRbVE0jjahISUqKNLBxCrwUgLOHrE6jjQ0Ttg0F6+2jLRguvzJ6bmMFKVrQelp+1GtYlDB/FLiX+aho0b6corkuCaekqHcQRKRrun2JXj+hcpzmy5Dvp7vvcGWDEuFOoJXo3dk8anpgXFPBpoykUG6Dv5tWJ0ypjq677u/D+ostHOsXCsPCDKHcr5RjuuD9yQSEPlBLk6125k3UbL6uB2UmPKVpU+rImcpp8rgu202QteG8PGcgFiklwh90vFM87gpXGYQMbJLpslCEsi2lFOEFYshYMkkiq2k/SQkhBhr771Pc29Bdws+rmv7fh4rV+PkVUbBTU5hlqZgHCDzlUyIj40O48WvkLVGMjWfgvjMbR93rdeIqj6G1afF+shMrVKKveC7bGp8oLLc6D8xGi33MBLus3t8St5qPzYWae/GfMrse5zjYLX7uegR5QWN8utYV2Yv/S85DFOs9vBRvx4kRiZoGo6v0k1ORmLJmcH6nbM+O49fXWu6+dtv9p5/aEMajZLLB15CZdWlfBYitopiuj/fLuzkAII/Eh7RfdIwyG3GiqfN2YH4NgHpSheLJ+go/iEQ3OwhZAo4O8v4L5WOo6MhHMCp7HyuUnrkbTCxTpAeU75dXsWDQ036LK2alADHMx1a13N6m3DArqKGmegZ9yZpuYUXQloA/CE3TQl5W+O114uqlMoQG9Qe11ckcvOuC6XvtOZK8lykb4qX/fhC2UGrBPwc3nFs3dnbKQD8GeLFqtJx9g3Fgv/5hEv4cyLArfBAy3eV+aQeMHl6485KcfDtgp+tW/J+jaIXvUvZrtAQkr+nkJaewnRz61sTH+nNeb3FjT5BjRn6ZbuYSrGjdpuB3IeWtT+Z/LPFATPEXnb1e5l6P95MdcoqTVCGscZ7wfA5BBK3+O3CWi2NTQLjo/xwbzk7tnfK4jY8Pysk/l6b7Cm2/xLgjzwlPB539DMWCmjQFgeJ0eWA1nKbC4A7HCdDH3kGXLTUfP7Wk2sTiDFL0F547TTrjitXFKdxkc7N1z65Lfzju4JR+qDIxD8l0TbeGXscVLZ/ZF1lmQKgiMVNdUxQIT/mN/qM6K9jEynAn0yc/XLQJ8qZ6sUJYYSW1+plfUgKPZBVgcb+NqghuJOz++Ao/qRU7gx4b8Ioyf42EX30gFxIdx40jdeLGbUiRluM4QZEWJIjgNuu2leuxPZE5/EkZk57hHp6BV8z4mCeaVG2oPVWgmJ889s4l1uBR/x0m6d3q8gIFQx2JKm53tPPXoK+n/Kdz8qolG4JibFNT+MJuQSMO4+9+tJTPOkIlyMaBG5UApLpwrEQe1d6NZifN2JVT14Pali2nuF4G3V57uKdeYmbQNH9DD60s7f5jA+gTut8nJdNSbcinqtB3yDWkb7syz3NeNdAhFGwZ5h8f3BGR+ZpHZXxGdo9iXIOxQivUk+WWmuPF2zp7Yez5L0dVERFz+HJJtdnXh4D2pen7tnR4+lyB46wmRaeP1u9B+sF+/I54GQK5qdAaEEbXkQtq4Vwza1kK/iK8Xhl2auMtrnRkMms5pvyzImy5/EENabsuO7PvO0ffTqfzZlSLN4+Nv4SRBpiCsY0e3vA6/N9qTmKm6H5ldNogOc5lQI7yUz6O+cWIb9sOhOfzKyDzOouZ79g2/1BloS/JuEhZgscdKC5iDxlP9e2xo8wIybPyGz6StUT6zcX753lxUuOD9/rYoeZ2Pjz6bGPY60FQvmQ4+0Kh3j3kDqVe/VRUC+N2ZVIi1GCykBFHcM4MEnu4tyUxXi30BehLHdJSHBlj9xnlxfwaZlRM+o8hbX+Xh+FmGlVde/lpKiPvKxsoFxXT8IPG+93lTHZyd8AuXvTfS150neL6AVfEjzYHAVAxSxsXwlpbwde7x3weYrPvpFhJgN5zRKnzb2il4p+yrMbfQaVfkqbZyig5s81KCmcjBTXW1fTB7efywPuuTfcXVRu5P62wfKOvO61Oa4vG8NFEME+EjfDOASTOD3Sgecf/lvLhn2XS2y270oMNsvQt1DhURO7nteqDriAxK2B1EG2HVXUdEKN+NfelfeA3897kX6+8L+eLS+qs+W3AVG9Lz/Po4jiLjVsRZ92Jgvy3MYFU0y6RmiIWMzuXfh+1EhUbjTnsAqc8gFRIK3+6c0Mn2bb6d3RB71Mx0Oaw0XyItDcnUZ5p+XkiVDwq0RBw+w2Ir9A6OiAhRdZdcLBjFq0Hck1KPfEcpDt16g+AU0yObbXxW/ph3fOwQTggXIvG77BMhmxpnA2Yta8PfPFkqba8zoYOvyvaOs1kCZv42CY5RVnMrzc6fJV44d0re9YoTLJhon3DbI2wyjKUZ5xAD8B16mHxX5Al9NZixC/HBF8PL56Qi9zCYGfaUs+sjE6dRbkwEVpyvxUmYH9GiQZ+sqo81DabVESS5qcGVxxPASGVJ1EWR7LK8CPJDrn1x4UMNMYgVjQRJ1nGRGCyWQMk5kTYdoN/U5HMJ+hsZlEFpudMHNo0pV1WXttq3oHuE9AYQJU47vmeWnLCcMSTOOzQiYH+wxKyZmAmol/UyETvl85UNBP6bC+rr/H80AuPmyaAATutxq6iKvegrByaV0pEsKXiTY0Ejy89uRoe27BP0YT4LfD7G2z4w4BuegIu92LM6TxKsl7+gx2eMVKkSAZ324XEDUpB+6x8qUiIBvPlMsSe5BwVPUzRrL+zXCM2bwcnCqhCEO62UVTCquww3q9P53RvN+cB4aQQ1lyPNyCoUTHNKP5qoEeH42baofzPo6CpAJK2jDr02sskIU/9pGXZLk4NzdSURT/68d7hPzyHmX/U+Xe/775COTTl+gHfzOygPDgDo7pxuPXCk0ltK7/sULHPYhf5oU/jQg/i2V/c7MYLP1MBb6OUQ8WBamN0HYzbGXfSKoShbYxbCnQXPhwghcb+eVof8Yr8jTCaa0669Za982fhbXC+BTEzyJe4ntwaP9liADl/zAwOOPP37/MLr9MD3+YX+D4/msxFbAMIMG0PQW/a9fzVHz1+MF27W620Ckw9eYr3T6KX4u3NnXov14w+J/h1u7h1v8ysxRi/Z8L0LbFhX+ZLDqr+93g8cW+mNKnt9LRV3RRp+40PyaZS7nFSwlA+Qq5Mx+Hw6BYQfn6t3q5KNDqtGuPr9DuSfX6tVgZ+j9eP5MWq7+MHT/98s9NJWX5D8wkTXj/ZiTBXkjaHX+YblCrBmiyRH8s4N+/DCH2b0aY/o8F/3/1mglQ779d928L8P+iiQXT3Cx4tQoitSlKgzb+PCgV/SwW17/VefxmOPmnBpffjTi/G3z+MqPQlyfQe/JvLcL/YUoxMan9MbL8Q2PJHyaAG8QSrL7/yw8V/3rv78rukdB2mWuBtrv/9wcof733twV4war1LgLzACl/jYOPlBHqgr7B+39tC1EXjdjm1lmtUZxvGXXhqqEmrFVIGd5eqYAYD53m0tlXq/shrP6LDw5HvnlpTtmpFdKqAocqvnn+2kayA9zPhpHQsbqobu4QlWqt/re3EP0v1P/PjT3//cYUr41YEdGF8FJ89widcI1Y7mfr1iq83VNxfo7ZjTrd0WpwT+i/uMXo/xGT//8ZUwZMddpSvcOf47RvDZU6cK/NH9u/RmX0RtrQB/3gqLjGWlVYh/8PY4rlqk5DaGwK5kXx32pM+WUs6c7xP6/V8fWv/A7GJkV5FMToX+3o2g3UBerQWtv9MZmAeH/jY+ybhOZEje6oTxU1wdzju6iCsYg1QUzzteZzqw76S3fEpyq4eFSb52/xhcWCt/2d2Q7xWObSaxW8fr33p9nuzzJ3gkbwF+WvyOX7HxPgv2f2+/N+tAHENSj/g19Updx/mXBc1Dv/MO78OafLMf3p5775y5DzdwbP34w+Pxj8h9HnN9Prz+e/m2lBu3/4xiXWFARCmsYB5eF5QJg43s2ke+2BJJN4/3ti1E6SxjXJOqCyjMtpfMHX6YFLL/MofeoFexhjfg0gUM0ZYXwWeflM5R3tE+H5zxd1vcyVUVMqhYAN+YNTLetrRa8TD14HEJnEtu3yrU7LNWaRQj8Sg5wSIcwiIp6nGQhCwcEfNGcFOLbvyMNY20efkVglCYJ2YH3fH6Eghn4djO8ed6WolZbH3dmSYjwrYg/UPvlmB/aZgSJ9aehQliqD0foTcGxZHr5oF491VNfvjJN5Afs+n8WbRViEpMjY2j54yNgjb177BckmQCMsT21ztenAVUU31jYaOy1e1uwrOVeMjbeWd/dK+AzlZoQC7FnJJyWeyXbVek2v6nY5Og0fvdbY/vCsZwx0BFIjSugXzmtkHjEfnr0DRFuKGztkeR93NsnEweWutS3NuCwJrncZzyWt1kNsZbEHuM9ViYD6fJaeOhB2ZPhrn7KP6CVx8XOfNBhz4mn3oNFsqgwavWnNr6ZFc3q/tTP3ckRYhIabou+Xr9g9Yh+XZtrfWCXGE67tWbMmjYAti5LjbqzwCkjtCTn31Q1hTJbXd8PNkeaMJcRXcVSpTthAV83WN/XQsSoUTaSbEI3OZzqC9Bi6aTUXPlulAIqzrd+61NUg7EXKXhBoMapYGVoEIyGuDxd2cTjY9vEIiJzP23Y4WzTS7rqFCXmkKW9mFT73mDDqRzhd726w4PbCRIfhK1vSjPqjrPn7zU8bhOXSUb7v+w1PVEg/2oJb7PPe7VshHXZK3M4e2UtXvVQWXVsbVrwtKqZ50jdeI6Z5XhPt4En7rVKRhCf7fPWtL+tv7i2uZH5q4cN515xpomT4mK5a9mbKyetV4ob0NfCCqsLEpWgGO302SBbH1+Q7mSGPJ0iR3PeLGdcsw4ZZvRVUUJFbEdi+KOnKUZZW7jkST3guMNLoSII03Wi+ez57VIyy2WkmaX2z+yu7bwN6bqwb2nTj+xEZ9NkrFgfQytFjQ7tZ7xGCuFqGECzmuPTEB9/KG23f6O9ncL4hEk2XyMtt53vRrOGdzYgfovUnBCr0vNu9dUlQkGWWN+tV1VKeMiXpC/+1LXkRsKQoDuRdad6gyYQjGZ9r8saVQQ28eHiCfKJw/+T4d2xsw1n0yrnBWMy/uy7xoGCmjZZzH/yEUEtEDI9OMb8z9vBegZe7AaO+wIRUH8twh7Sb3CEYp29x20nbvnjOw4WKL1LresR9fbMtZmssrDJSVcnsmp7IiFpJZJiOpWWHyAhq8hTUWNaMj/kSNMrXFuU7TdPSew/kRgyO97weDkUciFWScOsFeprSQJ7+YJpeZNNvSn0xfOkTfhS1c1qXhvisB7qsOSxVAuo4zpIV3pQ4ELPcttP6XWf7voufxe2T8Lv4sxNvTtdaE5Apy/lsn2SHBTNlRLF/I4jlYYv1s26PU8eT1kVS8Tyf4K78mVE0/SqYwlbntexauvDEiWHYShdx9VZHlhFx1tOyZrmqttg815i8+WypaevF5pAB7sY05hF7lDPlWQF1+q3j1mNMpny9K44MKJEzXcinnauvlbk+R3/yFALTbudyn1uqmfWPlbIISl2zm9aQVXV+BnROODjWqIzKhE/Ui3z1e8rS3igYdwxqfRXHm4lnkIoPzIGAXAPV7cf0up2I7NNx6jzz9eS614imW8k2yrB9EaEHqoRh3xlOq40YLWMUyVuM02SYhmpdnUpOlK68rUczXhvxGLEI/fapZQkIwstQ7M2CoDfYdO+gsW6pewv2xX3/02XVwTI6GKqtI9PjrOuvh9Jv+wMfi/YQfCuCGr31+7ZvJnOvktlSfo5DXbENyhfZQV7yN3zxpl210rc0PJG2rxXksTTF60qfxp0iQ/g0vdwP3iqnZI+CbgRndCD/ymDBHt+P0Vq5B1OwrOqRvkw9S6d4hV0lqEy2swYsjni0aXijv0XVlqeeOP2pcz0+oI9jw9TiJTVb9EXI5nK+Yg3albUn/1ZE8nRzFI5A+FxpczPKmkqYbU5sWlrGJyaDnR5YfSbyGa/ZD+S+PIFXA/MbwQrI59+6MygzBHkN0AE6Vz97Yb4loYq/1c0kg1iYjJHnqwhr3q7hi34pSup6SQuFntvdEAqZbBk+gybTyQgJwXQYnVoIYFOEnUpHjiM62hC2vguz6Jsfxc+GH58AdzZkzxbXiptk3JvoLIv+ohVqMdA16qvMQVHyy18Zjo4CNSzBI3iw758FzOvpnmsRF5z3ouozqGrGD5Fz1aL9MQBu8F3UYz4YRuJ6O3jxtHNOGY4Yirqc1+bdekqGlhhZHzdxAiTrClG0mSdZMCFn4X7ApTPaIf4OTbI6ogjm7gzDNHYmT0qkRB+QV8+fWG51RHBnqw4RYTh14emvn6dYt4wbp1tYnEGtYhqW7UNVJvIYTELCFLekA/xRh5coGD/PqznwI/jy6CP0yT5gVfXANKHPQpjvU/LcqwGEM7iiuJBw7ZBKGc9+JDd7+XieJeky1itmp83Fibirnkm5c/tC6nfvE1hGC0Ppv9XKfNV3jxsNZB6MAOYR0PXttfSOi2gfO1eo6fGJUx3iGKd08GjdQ9d0G8yhJf1eSPVZTbJRX/1ZY1yKHHHofhCx7QL0HmHSpB53PobNZW/9OH11r7RasdZATHl9oGV083oBVhJ10SVzVEe6u3+lAiACaliePaOpmyhOjqcGAJdJ5Is3IBdHiD/jzk/OLa+PDcfuKaMbgT2Ji5Rr+Dpp1pVFup/oGqaGeBhE0UkYTmyvalJ+jqAvazHdvC/hKOquRrOBA3RXlERzs9ErBY2RjiN1gs+JAM4kLUQ05grpxT2kcB8xODEe57nQYRH49qXKYs6tktXJAA1GjttEAQcJZVoeQEzJYBxum0idRzM7dGLIUQbYv+dj/Py528seI69r37QKG86pLQd9f7iU6FM8ajXpfVqgyQ6nPk/c4g3khfYfZgm9x09vNSvAE1k89BrEagtj9IdyXm8uWyWaPqyKlbgm3SGM3tacBUU92lEEQU6Hq46Zw6cBP3lzc7flsdb7S9DqCsCuxmFUhz7oT8txRcVyY9dC9fmuLF6Ag1Fu5tSAVZIpWk186KjeCFjwqMt3JcTROQPMz15FTRdRzYKEGazatqK0zwt+H1pV/ipeerM4Ub6O90cdNfeGHI5X3rqC1qhfoDyW+6U5lBcp7eg3Id82Hwtisvv5lLrtEI0z9HrZAgeAkDSYqbaPopy2jSChL76vb1Ohoue2tgvWheG50QuKNQ/m/Yq4Od9Ib9KfmMQDsmRfha1zFJ44xkimX2GWWhBDAGbbty1xj/r1fYKcgBeRuJE7DiEodK9432xoEkAbodgV4F9ZMD0CEowZmfPXGAwbuI7Ff0g2Rc6AF72I+Tm4YeLdtH3ugE+Sb1E0eKWdzKI4LY/LmINxT6wAeSJnBXFdUOSJ3l8He8TLOLry6q2r+eVHCwAFmfcRSne8557QisRJZtTwrSLo7MRo0kUNHrSxm81I9kBjy4pjxWwBAdTV45yoYVohwJXfV3uDodcY7BBk//zIgNhVn8hbHk7AXgPIuQayN2CmphX8COHvdiYB55VFKL13lwVDIi+93cdRmZ/vFnoX0dMsSHJ+zZNx5UtpPJZ2BfGHGWtdwqQ7PVbju8+0Tezee9/hT0C3k7RH4X6WqkL4WKHL0TK16UBa3CeFhQPV4Owby69JFsm6bOeCfbvi8AQCgZ6xtLyCtpnaHJqwIDayTdkT0ieORNjYoZqxWUlcJAxcB8gTwJ+xULyNhDXjL5xbIScuR25QMGxEKnfVEsDhcModCBCo1DUx2niMK44FdEd+VA//ibtcludL0MWuQwDTVUfP+yIL+o3BW+RjWpENQ3Cmh431Nie8RzQZ8kk3tzBQn+Os2gNFKXzOsLwSFKiKpET32gC5gk+fXajLEKUhPJNzBOCPYO2aUN5bUblQIOb35r0xJvZd8uERxBnzWeLk34YzsRf2oQKBGGLa8nTfCOHKDhVxufFsgaf2/LyopNyEjguPcx9yIq0OOT0Ug3q2pcBCK9BqdB+EZvnl0nrnrZrlde8baANczC5om0MCqoeLzRUAZnFo3sU838UtbMs+tDemjtUkBRlOYGeSrCh0vNiiUp5Y8Q2fd8Dm6Kfif06CFZtXSM6zuNeQWG7rvVxiRLCH96SFfXszK9aSmYcbZcc77mKatZPTFCTp68e4oODSfDIyEiVfV3SArkgQfMgHTfikaSMW5ZvkcxAf0Y87BegIQghaTXhpExAoHpYFA1mjmyYmlc4JMuITtDhUPZ7NXvhIJFvdC3p7O3spBV1mQx64nPXilFkJUhpMVmJr31RTCvUa7bveeg2ks3afrFQgoiAh6LD8BHkT/wiCoqmNEd9W/Dnoi1TmF4ol8exmkmiGa9zHetP5a6XAOBrW5Y+GaL+OPXj+QvqnKquf1/vjruQiMqYUAZ3EvMPvEbu48UmiNU8IyP/miEvMHrF107QTIf5o1WYKcpDhSK8BGmfiGZVKX+FwgPyiZ6/FuXNFChFFs73N7mh6zj4Mq6IhQQdr4LqYbBs0Pq0m6TocgEzRLN7vT9euWPA8q7xwPlAoxSvxqQNzjJF9+4Lib3lPnTDLCH/NMjpjqaKwvkRolVnjBxEXgba6sHtm0XCzO+y/GKBaI/qcliiEGVEP+hGiGMMYfx4c96+ZXcDn5SeE4vKgxKm6pbnhXd/cSnze3OJtEDHHixerq36/5SQ1Mrr6XgxdjEUIOuX2tVWg63PQVUNVJ01mE4D7dSz+vedZr0S4mt5PstZFLb3PEgBQFNNArzPvN5L45Vt4fkE+DaXWR/ItphKzl4kp4yqrkpVncwhJqtK0YDECoz7QDPsULyQH1yCVqb/TfmnrVgcJMZOYcnOaM0ey6mRlOfYfTFm+OTUM34NSPAClIb7atHpzTg5c44ykuizHixHsGC8ovF4Wy5xQNSpybnrWxGGj5Lnc6s11Xfwl/ToZ6Q9UG4K403VP1YcuQqWe458pcEklZWuDL6mHcRs0B5N+yqTadLF5WAAKiP1sWiXWXy0lBzkYR4vlOjsxTPpBHyXcqjg7FxGjVRTOH+oLczd1icyVXmnNvlKJLFcTCDBGfHVf7unjfhWu0yJ5Xr6bR20lq0XT+Bs/iuKJ8v5hXr3nbVJ6vor8ba6WrkJHLRodP5tpNYlUYb2q1EmhkAp0NA3Gg+GYQZR0CO7sUyTe8svkBj+PkKblaaWJXctq9etIOWO2izbZxIoN1+xu9YyYrYy4AP5PTyY13k/FTM+7P+AA0dHW9b4omvESOwTu/FEfa/N2Rjl8twwFglryG1uCTOndDGkFBKo+4tj65d3seNa9NgKQM970hgTEOqJjwjOHrCustJWvVzVNAwTIkWxhlY5drgiavxM9PDuekagiPAPcXmhOSKKoH7PvEwEBSdSbRk1UBVlPr/WJfNx23H0y7oPcPcI6/XTlYIAfbdeKRwCSDfV9WcIDxwqJCcLrKd7vSZ2X6ridr0Hl0gf5FIyi0ORl6BRIs6/n2iGPHdRfUdIFblY9HuWKMk1OAImmnP2rNgoa5OGPGuCWIDoGirK7+3APVqaqUq662CPVN+V2pvV6J9oDwy5PDoEem7Pt6+XvzJ/zZW8eQI9TWvFgO1mcfd5ry9WuueN5nArIrS302NHuF4cTNMhsvPMO9OSbKyjxiITWf+d3IZLIRt5puz3s054DG3kA1pwJfhC38Rw/MSfXNuyhg0mGoAHSwtN33czxtu+HR2NnRq/9l+y374/egjIN9EPT2R/NOHU64/uchZrWJRIf6IPJ3pGP9kXwKuqcBnK+cgIkjN/7XLhPyCD6Fv8oYGb4ELwvKGA++zOSj9PoSee0BtPpBkb3tiSkj993o2f4E4YbG5Ea9KHeKUzzTWBtxwRpoVDJ0jqt30kdu6ZX6EcFmZeH8+8duVRmk3l7cg6VER6HoUNyMYoZI7DB3UL2qCcVF0/8IM9Tcn+EE8vqZBIsFejlBnVG7qseO352hGkgWY8N7YnuhOwVt5/cnPl6nkqyBg+OeuDhT370GwPPTI0y4mj0GfEtDWXZ+V4YryXtedaDFyTKPJ+elxwGA7DyEmuoiB/zKqQ/p5PHiUw/N16RUbpHHi6gZNBggViFziTfsqHVnOU67tAVwrrDsPak044YoqW6DaU8BSGizejD2GJqgfRP+uuGGc9XBWr3piQ7uN5V0GQAtba7hlQ6RBI09tEzr+w+VM44pKAZ2CNNW9sfNcd9rGv+guNunj5856NPhBDhy46EkDOXM2p3nwd6yc9GEmtTkQhQs2nCslvIBgccxHnbwgR+Hspn9NopHn0c2h8IbrV8hy0jgAGn1l+nx8dfZ6a9zZE+gsyuX6XZ7ETKjR2Iz4gKkEf0ptbP3ijkpj6NomFMTYdPME7KtU5eYjzd0Y40Ds1dy+EpDH0Y4kxFPOduz6kKXp3w9HJ71V487j0jn7g2BNrWATflbnrSvmCfEuG751kGVRmxreow8qvvo7btSoEPIRkZg+dBZ9o80w2e6wJafjVtMj5l9PP9iuwsgO23nYWjwyLNbD62oabsDpFchpqGAPuEFvGYTAmnigS4V3md3ya3H7NZB6FGRZieJfCILlv+hIDRbfDirK4NHQAkpeSFrpAcvAnIrcztKn/mwb1tKQnyxDfTzLOUmi6e12yM1g7O9ZvCdnTW+ReJy9Oaf7c7bEyF+TAv6uiTJcME9YZ3h1ZQXn8gDRRCrQu4Sy2YhqZPmmcbHDetQqNhpxFQDiOc1wURRjZjmU6rTf5drxNW1ppyNcyJvghKVe3nqmG/WtBJzjy7F7kN8aEzZDbVu2bDHZ2KlprNcU0/VM2hlpf59GDSTFAIQxGrCIi6CN/x3gmJ+GAq6KkDcoDgzgKv3aWwEImxWpe6yaK9sXs463qggcRYg3rp/RYQtLeiC9gjAbHDt7OghgnQ5lnpoHL9SgxlbTtBjZLmMvFZ17BkrMzJ1e+poyMIVc5EUtivpz6UsHOgh0h5p8VDvpqecApmjphrD8qAuz18Bl+/jOF/tKER9T/+4z/+Nw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Rede Social" = _t, base64 = _t, Ordem = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Rede Social", type text}, {"base64", type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado","iVBORw0KG","data:image/png;base64,iVBORw0KG",Replacer.ReplaceText,{"base64"}),
				    #"Linhas Classificadas" = Table.Sort(#"Valor Substituído",{{"Ordem", Order.Ascending}})
				in
				    #"Linhas Classificadas"

	annotation PBI_ResultType = Table

